// packages/scripts/generate-eslint-zones.ts
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

export interface ZoneEntry {
  target: string;
  from: string;
  message: string;
}

export interface GenerateZonesOptions {
  repoRoot: string;
  outputDir: string;
  /** Override module name discovery for testing. */
  discoverModuleNames?: (repoRoot: string) => string[];
}

export interface GenerateZonesResult {
  moduleNames: string[];
  zoneCount: number;
  outputPath: string;
  inputHash: string;
}

export function discoverModuleNamesFromDisk(repoRoot: string): string[] {
  const modulesDir = join(repoRoot, "packages", "modules");
  if (!existsSync(modulesDir)) return [];
  return readdirSync(modulesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(modulesDir, d.name, "module.config.ts")))
    .map((d) => d.name)
    .sort(); // deterministic ordering
}

export function buildZones(moduleNames: string[]): ZoneEntry[] {
  const zones: ZoneEntry[] = [];
  for (const target of moduleNames) {
    for (const from of moduleNames) {
      if (target === from) continue;
      zones.push({
        target: `./packages/modules/${target}/**`,
        from: `./packages/modules/${from}/**`,
        message: `${target} must not import ${from}. Use packages/contract instead.`,
      });
    }
  }
  return zones;
}

export function generateEslintZones(opts: GenerateZonesOptions): GenerateZonesResult {
  const { repoRoot, outputDir, discoverModuleNames = discoverModuleNamesFromDisk } = opts;

  const moduleNames = discoverModuleNames(repoRoot);
  const zones = buildZones(moduleNames);

  const inputHash = createHash("sha256")
    .update(JSON.stringify(moduleNames))
    .digest("hex");

  mkdirSync(outputDir, { recursive: true });

  const header =
    `// AUTO-GENERATED by generate-eslint-zones.ts — do not edit.\n` +
    `// input_hash: sha256:${inputHash} (informational only — not a CI gate)\n` +
    `// Zones: ${zones.length} (${moduleNames.length} modules, N*(N-1) pairs)\n`;

  const zonesJson = JSON.stringify(zones, null, 2);
  // STILL-OPEN-3a fix: emit .mjs (pure ESM) not .ts.
  // Node ESM can dynamically import .mjs at runtime without a TS loader.
  // TypeScript fields (interface, type annotations, "as const") are NOT valid in .mjs —
  // use plain JS object array. ESLint's import/no-restricted-paths only needs the
  // { target, from, message } shape; TypeScript types are not needed at eslint.config.mjs runtime.
  const content =
    `${header}\n` +
    `// @ts-check\n` +
    `export const GENERATED_MODULE_ZONES = ${zonesJson};\n`;

  // STILL-OPEN-3a: output file is .mjs, not .ts
  const outputPath = join(outputDir, "eslint-zones.mjs");
  writeFileSync(outputPath, content);

  return { moduleNames, zoneCount: zones.length, outputPath, inputHash };
}

// ── CLI entrypoint ────────────────────────────────────────────────────────────

if (process.argv[1]?.endsWith("generate-eslint-zones.ts")) {
  const repoRoot = resolve(process.cwd());
  const outputDir = join(repoRoot, "packages", "shell", "src", "_generated");
  const result = generateEslintZones({ repoRoot, outputDir });
  console.log(
    `generate-eslint-zones: ${result.moduleNames.length} modules → ${result.zoneCount} zones (hash ${result.inputHash.slice(0, 8)}…)`
  );
}
