"""Pre-built report library: 50+ reports across 9 categories.

All report definitions here are system-level (tenant_id=None),
available to all tenants out of the box.
"""

from __future__ import annotations

from typing import Any

from src.utils.constants import (
    CATEGORY_ACTUARIAL,
    CATEGORY_BILLING_AP,
    CATEGORY_BILLING_AR,
    CATEGORY_CLAIMS,
    CATEGORY_FINANCIAL,
    CATEGORY_FWA,
    CATEGORY_QUALITY,
    CATEGORY_REGULATORY,
    CATEGORY_UTILIZATION,
    FREQ_ANNUALLY,
    FREQ_DAILY,
    FREQ_MONTHLY,
    FREQ_ON_DEMAND,
    FREQ_QUARTERLY,
    FREQ_WEEKLY,
)


def _col(
    field: str, label: str, col_type: str = "string", fmt: str | None = None
) -> dict[str, Any]:
    return {
        "field": field,
        "label": label,
        "type": col_type,
        "format": fmt,
        "sortable": True,
        "filterable": True,
    }


def _currency(field: str, label: str) -> dict[str, Any]:
    return _col(field, label, "decimal", "currency")


def _date(field: str, label: str) -> dict[str, Any]:
    return _col(field, label, "date", "date")


def _int(field: str, label: str) -> dict[str, Any]:
    return _col(field, label, "integer", "integer")


PREBUILT_REPORTS: list[dict[str, Any]] = [
    # ── Claims (8 reports) ─────────────────────────────────────────────────────
    {
        "name": "Claims Volume Summary",
        "description": "Total claims by program, by date, with trend",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_DAILY,
        "columns": [
            _date("fill_date", "Fill Date"),
            _col("program_id", "Program"),
            _int("claim_count", "Claim Count"),
            _currency("total_paid", "Total Paid"),
            _currency("plan_paid", "Plan Paid"),
            _currency("member_pay", "Member Pay"),
        ],
        "summary_row": {"claim_count": "sum", "total_paid": "sum"},
        "chart_type": "line",
        "contains_phi": False,
    },
    {
        "name": "Claims Detail",
        "description": "All claims with full field detail, filterable",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("claim_id", "Claim ID"),
            _date("fill_date", "Fill Date"),
            _col("rx_number", "Rx Number"),
            _col("ndc", "NDC"),
            _col("drug_name", "Drug Name"),
            _int("days_supply", "Days Supply"),
            _col("pharmacy_npi", "Pharmacy NPI"),
            _col("prescriber_npi", "Prescriber NPI"),
            _col("member_id", "Member ID"),
            _currency("amount_paid", "Amount Paid"),
            _col("status", "Status"),
        ],
        "contains_phi": True,
    },
    {
        "name": "Top Pharmacies by Volume",
        "description": "Pharmacy ranking by claim count and dollars",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("pharmacy_npi", "NPI"),
            _col("pharmacy_name", "Pharmacy Name"),
            _int("claim_count", "Claim Count"),
            _currency("total_paid", "Total Paid"),
        ],
        "default_sort": {"field": "claim_count", "direction": "desc"},
        "contains_phi": False,
    },
    {
        "name": "Top NDCs by Volume",
        "description": "Drug ranking by claim count and dollars",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("ndc", "NDC"),
            _col("drug_name", "Drug Name"),
            _int("claim_count", "Claim Count"),
            _currency("total_paid", "Total Paid"),
        ],
        "default_sort": {"field": "total_paid", "direction": "desc"},
        "contains_phi": False,
    },
    {
        "name": "Top Prescribers by Volume",
        "description": "Prescriber ranking by script count",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("prescriber_npi", "NPI"),
            _col("prescriber_name", "Prescriber Name"),
            _col("specialty", "Specialty"),
            _int("script_count", "Script Count"),
            _currency("total_paid", "Total Paid"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Reversal Report",
        "description": "All reversals with original claim reference",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_WEEKLY,
        "default_filters": {"reversal_flag": True},
        "columns": [
            _col("claim_id", "Claim ID"),
            _col("original_claim_id", "Original Claim ID"),
            _date("reversal_date", "Reversal Date"),
            _col("reversal_reason", "Reason"),
            _currency("reversed_amount", "Reversed Amount"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Compound Claims",
        "description": "All compound claims with ingredient detail",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "default_filters": {"compound_flag": True},
        "columns": [
            _col("claim_id", "Claim ID"),
            _date("fill_date", "Fill Date"),
            _col("pharmacy_name", "Pharmacy"),
            _int("ingredient_count", "Ingredients"),
            _currency("compound_cost", "Compound Cost"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Claims by Therapeutic Class",
        "description": "Volume and cost grouped by therapeutic class",
        "category": CATEGORY_CLAIMS,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("therapeutic_class", "Therapeutic Class"),
            _int("claim_count", "Claim Count"),
            _currency("total_paid", "Total Paid"),
            _col("pct_of_total", "% of Total"),
        ],
        "calculated_fields": [
            {
                "name": "pct_of_total",
                "formula": "percentage",
                "numerator": "total_paid",
                "denominator": "grand_total_paid",
            }
        ],
        "contains_phi": False,
    },
    # ── Billing AP (7 reports) ─────────────────────────────────────────────────
    {
        "name": "AP Summary",
        "description": "Total payables by pay-to entity, by period",
        "category": CATEGORY_BILLING_AP,
        "data_source": "billing_ap",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("pay_to_npi", "Pay-To NPI"),
            _col("pay_to_name", "Pay-To Name"),
            _col("billing_period", "Billing Period"),
            _int("record_count", "Records"),
            _currency("total_amount", "Total Amount"),
        ],
        "summary_row": {"total_amount": "sum"},
        "contains_phi": False,
    },
    {
        "name": "Payment Batch Summary",
        "description": "Batch totals, payment counts, by vendor",
        "category": CATEGORY_BILLING_AP,
        "data_source": "billing_ap",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("batch_id", "Batch ID"),
            _date("batch_date", "Batch Date"),
            _col("vendor", "Vendor"),
            _int("payment_count", "Payments"),
            _currency("batch_total", "Batch Total"),
            _col("status", "Status"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Settlement Status",
        "description": "Payments pending, settled, returned",
        "category": CATEGORY_BILLING_AP,
        "data_source": "billing_ap",
        "default_schedule": FREQ_DAILY,
        "columns": [
            _col("payment_id", "Payment ID"),
            _col("pay_to_name", "Pay-To"),
            _currency("amount", "Amount"),
            _col("status", "Status"),
            _date("settlement_date", "Settlement Date"),
        ],
        "default_groupings": {"field": "status"},
        "contains_phi": False,
    },
    {
        "name": "ACH Return Report",
        "description": "All returns with codes and actions taken",
        "category": CATEGORY_BILLING_AP,
        "data_source": "billing_ap",
        "default_schedule": FREQ_WEEKLY,
        "columns": [
            _col("payment_id", "Payment ID"),
            _col("return_code", "Return Code"),
            _col("return_reason", "Reason"),
            _date("return_date", "Return Date"),
            _currency("returned_amount", "Returned Amount"),
            _col("action_taken", "Action"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Carryover Report",
        "description": "Outstanding carryovers by entity",
        "category": CATEGORY_BILLING_AP,
        "data_source": "billing_ap",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("entity_npi", "Entity NPI"),
            _col("entity_name", "Entity Name"),
            _currency("carryover_amount", "Carryover Amount"),
            _int("periods_outstanding", "Periods Outstanding"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Pharmacy Payment History",
        "description": "All payments to a specific pharmacy over time",
        "category": CATEGORY_BILLING_AP,
        "data_source": "billing_ap",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("payment_id", "Payment ID"),
            _date("payment_date", "Payment Date"),
            _col("payment_method", "Method"),
            _currency("amount", "Amount"),
            _col("status", "Status"),
            _col("batch_id", "Batch ID"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Payment Method Distribution",
        "description": "Volume by payment method (ACH, Echo, check)",
        "category": CATEGORY_BILLING_AP,
        "data_source": "billing_ap",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("payment_method", "Method"),
            _int("payment_count", "Count"),
            _currency("total_amount", "Total Amount"),
            _col("pct_of_total", "% of Total"),
        ],
        "chart_type": "pie",
        "contains_phi": False,
    },
    # ── Billing AR (6 reports) ─────────────────────────────────────────────────
    {
        "name": "Invoice Summary",
        "description": "All invoices by client, by status",
        "category": CATEGORY_BILLING_AR,
        "data_source": "billing_ar",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("invoice_id", "Invoice ID"),
            _col("client_name", "Client"),
            _date("invoice_date", "Invoice Date"),
            _date("due_date", "Due Date"),
            _currency("total_amount", "Total"),
            _currency("amount_paid", "Paid"),
            _currency("amount_due", "Outstanding"),
            _col("status", "Status"),
        ],
        "contains_phi": False,
    },
    {
        "name": "AR Aging",
        "description": "Outstanding receivables by aging bucket",
        "category": CATEGORY_BILLING_AR,
        "data_source": "billing_ar",
        "default_schedule": FREQ_WEEKLY,
        "columns": [
            _col("client_name", "Client"),
            _currency("bucket_0_30", "0-30 Days"),
            _currency("bucket_31_60", "31-60 Days"),
            _currency("bucket_61_90", "61-90 Days"),
            _currency("bucket_91_120", "91-120 Days"),
            _currency("bucket_121_plus", "121+ Days"),
            _currency("total_outstanding", "Total"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Client Payment History",
        "description": "All payments received from a client",
        "category": CATEGORY_BILLING_AR,
        "data_source": "billing_ar",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _date("payment_date", "Payment Date"),
            _col("invoice_id", "Invoice ID"),
            _col("payment_method", "Method"),
            _currency("amount", "Amount"),
            _col("reference", "Reference"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Fee Summary",
        "description": "Fees calculated by type, by program",
        "category": CATEGORY_BILLING_AR,
        "data_source": "billing_ar",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("program_id", "Program"),
            _col("fee_type", "Fee Type"),
            _int("claim_count", "Claims"),
            _currency("fee_amount", "Fee Amount"),
        ],
        "summary_row": {"fee_amount": "sum"},
        "contains_phi": False,
    },
    {
        "name": "Revenue by Client",
        "description": "Total revenue (fees) by client, by period",
        "category": CATEGORY_BILLING_AR,
        "data_source": "billing_ar",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("client_name", "Client"),
            _col("billing_period", "Period"),
            _currency("total_revenue", "Revenue"),
        ],
        "chart_type": "bar",
        "contains_phi": False,
    },
    {
        "name": "Overdue Invoices",
        "description": "Invoices past due date with days outstanding",
        "category": CATEGORY_BILLING_AR,
        "data_source": "billing_ar",
        "default_schedule": FREQ_DAILY,
        "default_filters": {"status": "overdue"},
        "columns": [
            _col("invoice_id", "Invoice ID"),
            _col("client_name", "Client"),
            _date("due_date", "Due Date"),
            _int("days_outstanding", "Days Outstanding"),
            _currency("amount_due", "Amount Due"),
        ],
        "default_sort": {"field": "days_outstanding", "direction": "desc"},
        "contains_phi": False,
    },
    # ── Financial (8 reports) ──────────────────────────────────────────────────
    {
        "name": "Financial Journal Summary",
        "description": "All journal entries by category, by period",
        "category": CATEGORY_FINANCIAL,
        "data_source": "journal",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("category", "Category"),
            _col("billing_period", "Period"),
            _currency("total_debit", "Total Debit"),
            _currency("total_credit", "Total Credit"),
            _currency("net", "Net"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Cash Flow Report",
        "description": "Payments out (AP) vs payments in (AR) by period",
        "category": CATEGORY_FINANCIAL,
        "data_source": "journal",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("period", "Period"),
            _currency("ap_out", "AP Out"),
            _currency("ar_in", "AR In"),
            _currency("net_cash_flow", "Net Cash Flow"),
        ],
        "chart_type": "bar",
        "contains_phi": False,
    },
    {
        "name": "Client Profitability",
        "description": "Fees collected minus operational costs per client",
        "category": CATEGORY_FINANCIAL,
        "data_source": "journal",
        "default_schedule": FREQ_QUARTERLY,
        "columns": [
            _col("client_name", "Client"),
            _col("period", "Period"),
            _currency("fees_collected", "Fees"),
            _currency("operational_costs", "Costs"),
            _currency("profit", "Profit"),
            _col("margin_pct", "Margin %"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Prefund Status",
        "description": "Current balance, burn rate, projection per client",
        "category": CATEGORY_FINANCIAL,
        "data_source": "journal",
        "default_schedule": FREQ_DAILY,
        "columns": [
            _col("client_name", "Client"),
            _currency("current_balance", "Balance"),
            _currency("daily_burn_rate", "Daily Burn Rate"),
            _int("days_remaining", "Days Remaining"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Program Financial Summary",
        "description": "Total spend, fees, recoveries per program",
        "category": CATEGORY_FINANCIAL,
        "data_source": "journal",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("program_name", "Program"),
            _currency("total_spend", "Total Spend"),
            _currency("total_fees", "Fees"),
            _currency("total_recoveries", "Recoveries"),
            _currency("net_spend", "Net Spend"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Period Close Report",
        "description": "Full financial summary for closed period",
        "category": CATEGORY_FINANCIAL,
        "data_source": "journal",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("period", "Period"),
            _int("total_claims", "Claims"),
            _currency("ap_total", "AP Total"),
            _currency("ar_total", "AR Total"),
            _currency("net_position", "Net Position"),
        ],
        "contains_phi": False,
    },
    {
        "name": "GL Export Report",
        "description": "Journal entries formatted for accounting export",
        "category": CATEGORY_FINANCIAL,
        "data_source": "journal",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _date("entry_date", "Date"),
            _col("gl_account", "GL Account"),
            _col("description", "Description"),
            _currency("debit", "Debit"),
            _currency("credit", "Credit"),
            _col("reference", "Reference"),
        ],
        "contains_phi": False,
    },
    {
        "name": "1099 Summary",
        "description": "Annual payment totals by payee for tax reporting",
        "category": CATEGORY_FINANCIAL,
        "data_source": "billing_ap",
        "default_schedule": FREQ_ANNUALLY,
        "columns": [
            _col("payee_name", "Payee Name"),
            _col("payee_tin", "TIN"),
            _col("payee_address", "Address"),
            _currency("annual_total", "Annual Total"),
            _col("form_type", "Form Type"),
        ],
        "contains_phi": False,
    },
    # ── FWA (7 reports) ────────────────────────────────────────────────────────
    {
        "name": "FWA Summary Dashboard",
        "description": "Flags by severity, by rule, by entity type",
        "category": CATEGORY_FWA,
        "data_source": "fwa",
        "default_schedule": FREQ_DAILY,
        "columns": [
            _col("severity", "Severity"),
            _col("entity_type", "Entity Type"),
            _col("rule_name", "Rule"),
            _int("flag_count", "Flags"),
            _currency("total_at_risk", "Amount At Risk"),
        ],
        "chart_type": "bar",
        "contains_phi": False,
    },
    {
        "name": "Pharmacy Risk Scorecard",
        "description": "All pharmacies ranked by composite risk score",
        "category": CATEGORY_FWA,
        "data_source": "fwa",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("pharmacy_npi", "NPI"),
            _col("pharmacy_name", "Name"),
            _col("risk_score", "Risk Score"),
            _col("risk_tier", "Tier"),
            _int("flag_count", "Flags"),
            _col("status", "Status"),
        ],
        "default_sort": {"field": "risk_score", "direction": "desc"},
        "contains_phi": False,
    },
    {
        "name": "Investigation Status",
        "description": "Open investigations by type, by priority, by age",
        "category": CATEGORY_FWA,
        "data_source": "fwa",
        "default_schedule": FREQ_WEEKLY,
        "columns": [
            _col("investigation_id", "ID"),
            _col("entity_name", "Entity"),
            _col("investigation_type", "Type"),
            _col("priority", "Priority"),
            _date("opened_date", "Opened"),
            _int("days_open", "Days Open"),
            _col("status", "Status"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Recovery Report",
        "description": "Recovery amounts by status (estimated, demanded, collected)",
        "category": CATEGORY_FWA,
        "data_source": "fwa",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("entity_name", "Entity"),
            _currency("estimated_recovery", "Estimated"),
            _currency("demanded_amount", "Demanded"),
            _currency("collected_amount", "Collected"),
            _col("status", "Status"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Accumulator Impact",
        "description": "Financial impact of accumulators by plan, by member",
        "category": CATEGORY_FWA,
        "data_source": "fwa",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("plan_id", "Plan"),
            _col("member_id", "Member ID"),
            _currency("accumulator_impact", "Accumulator Impact"),
            _col("accumulator_type", "Type"),
        ],
        "contains_phi": True,
    },
    {
        "name": "Rule Effectiveness",
        "description": "Which detection rules produce the most confirmed findings",
        "category": CATEGORY_FWA,
        "data_source": "fwa",
        "default_schedule": FREQ_QUARTERLY,
        "columns": [
            _col("rule_name", "Rule"),
            _int("total_flags", "Total Flags"),
            _int("confirmed_findings", "Confirmed"),
            _col("confirmation_rate", "Confirmation Rate"),
            _currency("total_recovered", "Total Recovered"),
        ],
        "default_sort": {"field": "confirmed_findings", "direction": "desc"},
        "contains_phi": False,
    },
    {
        "name": "Audit Summary",
        "description": "Audit findings by pharmacy, by type, by outcome",
        "category": CATEGORY_FWA,
        "data_source": "fwa",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("pharmacy_npi", "Pharmacy NPI"),
            _col("pharmacy_name", "Pharmacy"),
            _col("audit_type", "Audit Type"),
            _date("audit_date", "Audit Date"),
            _col("outcome", "Outcome"),
            _currency("recovery_amount", "Recovery"),
        ],
        "contains_phi": False,
    },
    # ── Utilization (6 reports) ────────────────────────────────────────────────
    {
        "name": "Drug Utilization Review",
        "description": "Utilization patterns by drug, class, with trends",
        "category": CATEGORY_UTILIZATION,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("drug_name", "Drug Name"),
            _col("therapeutic_class", "Class"),
            _int("claim_count", "Claims"),
            _int("unique_members", "Members"),
            _currency("total_cost", "Total Cost"),
            _col("trend_pct", "Trend %"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Generic vs Brand",
        "description": "Generic fill rate by program, by pharmacy",
        "category": CATEGORY_UTILIZATION,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("program_id", "Program"),
            _col("pharmacy_name", "Pharmacy"),
            _int("generic_fills", "Generic Fills"),
            _int("brand_fills", "Brand Fills"),
            _col("generic_rate", "Generic Rate"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Specialty Drug Report",
        "description": "High-cost specialty medication utilization",
        "category": CATEGORY_UTILIZATION,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("drug_name", "Drug Name"),
            _col("therapeutic_area", "Therapeutic Area"),
            _int("claim_count", "Claims"),
            _int("unique_members", "Members"),
            _currency("total_cost", "Total Cost"),
            _currency("cost_per_member", "Cost / Member"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Prior Authorization Summary",
        "description": "PA requests, approvals, denials, turnaround time",
        "category": CATEGORY_UTILIZATION,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("drug_name", "Drug"),
            _int("pa_requests", "Requests"),
            _int("approvals", "Approvals"),
            _int("denials", "Denials"),
            _col("approval_rate", "Approval Rate"),
            _col("avg_turnaround_hours", "Avg Turnaround (hrs)"),
        ],
        "contains_phi": False,
    },
    {
        "name": "Refill Adherence",
        "description": "PDC (proportion of days covered) by member, by drug class",
        "category": CATEGORY_UTILIZATION,
        "data_source": "claims",
        "default_schedule": FREQ_QUARTERLY,
        "columns": [
            _col("drug_class", "Drug Class"),
            _col("member_id", "Member ID"),
            _col("current_pdc", "PDC"),
            _col("adherence_status", "Status"),
        ],
        "contains_phi": True,
    },
    {
        "name": "GLP-1 Utilization",
        "description": "GLP-1 specific utilization and cost trending",
        "category": CATEGORY_UTILIZATION,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "default_filters": {"drug_class": "GLP-1"},
        "columns": [
            _col("drug_name", "Drug Name"),
            _date("fill_date", "Fill Date"),
            _int("claim_count", "Claims"),
            _int("unique_members", "Members"),
            _currency("total_cost", "Total Cost"),
        ],
        "chart_type": "line",
        "contains_phi": False,
    },
    # ── Regulatory (4 reports) ─────────────────────────────────────────────────
    {
        "name": "2026 CAA Transparency Report",
        "description": "Net drug spending, rebates, spread pricing per HHS/DOL/Treasury format",
        "category": CATEGORY_REGULATORY,
        "data_source": "journal",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("section", "Section"),
            _col("metric", "Metric"),
            _col("value", "Value"),
            _col("period", "Period"),
        ],
        "required_permission": "regulatory_reporting",
        "contains_phi": False,
        "is_system": True,
    },
    {
        "name": "DIR Reporting",
        "description": "Direct and indirect remuneration for Medicare Part D",
        "category": CATEGORY_REGULATORY,
        "data_source": "journal",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("contract_id", "Contract ID"),
            _col("dir_type", "DIR Type"),
            _currency("dir_amount", "DIR Amount"),
            _col("period", "Period"),
        ],
        "required_permission": "regulatory_reporting",
        "contains_phi": False,
    },
    {
        "name": "State Regulatory Submissions",
        "description": "State-specific PBM reporting requirements",
        "category": CATEGORY_REGULATORY,
        "data_source": "journal",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("state", "State"),
            _col("report_type", "Report Type"),
            _col("submission_period", "Period"),
            _col("status", "Status"),
        ],
        "required_permission": "regulatory_reporting",
        "contains_phi": False,
    },
    {
        "name": "Government Exclusion Screening Report",
        "description": "OIG/SAM screening results and matches",
        "category": CATEGORY_REGULATORY,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("entity_npi", "NPI"),
            _col("entity_name", "Name"),
            _col("entity_type", "Type"),
            _date("screen_date", "Screen Date"),
            _col("result", "Result"),
            _col("match_detail", "Match Detail"),
        ],
        "contains_phi": False,
    },
    # ── Quality / Star Ratings (4 reports) ────────────────────────────────────
    {
        "name": "Star Ratings Dashboard",
        "description": "Medicare quality measures tracking (D-Star measures)",
        "category": CATEGORY_QUALITY,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("measure_id", "Measure ID"),
            _col("measure_name", "Measure"),
            _col("current_rate", "Current Rate"),
            _col("target", "Target"),
            _col("status", "Status"),
        ],
        "chart_type": "bar",
        "contains_phi": False,
    },
    {
        "name": "PDC Adherence Measures",
        "description": "Adherence rates for statins, RAS antagonists, diabetes meds",
        "category": CATEGORY_QUALITY,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("drug_class", "Drug Class"),
            _col("measure_id", "Measure"),
            _int("eligible_members", "Eligible"),
            _int("adherent_members", "Adherent"),
            _col("pdc_rate", "PDC Rate"),
            _col("status", "Status"),
        ],
        "contains_phi": False,
    },
    {
        "name": "MTM Completion Rate",
        "description": "CMR completion tracking for Star Ratings",
        "category": CATEGORY_QUALITY,
        "data_source": "claims",
        "default_schedule": FREQ_MONTHLY,
        "columns": [
            _col("period", "Period"),
            _int("eligible_members", "Eligible"),
            _int("completed_cmrs", "Completed CMRs"),
            _col("completion_rate", "Completion Rate"),
            _col("target", "Target"),
        ],
        "contains_phi": False,
    },
    {
        "name": "CAHPS Indicators",
        "description": "Member satisfaction indicators correlated with pharmacy benefit",
        "category": CATEGORY_QUALITY,
        "data_source": "members",
        "default_schedule": FREQ_QUARTERLY,
        "columns": [
            _col("indicator", "CAHPS Indicator"),
            _col("score", "Score"),
            _col("benchmark", "Benchmark"),
            _col("status", "Status"),
        ],
        "contains_phi": False,
    },
    # ── Actuarial (6 reports) ──────────────────────────────────────────────────
    {
        "name": "Prospective Cost Model",
        "description": "Project costs under different formulary/network scenarios",
        "category": CATEGORY_ACTUARIAL,
        "data_source": "journal",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("scenario", "Scenario"),
            _currency("projected_cost", "Projected Cost"),
            _currency("estimated_savings", "Est. Savings"),
            _col("savings_pct", "Savings %"),
        ],
        "required_permission": "actuarial",
        "contains_phi": False,
    },
    {
        "name": "Formulary Impact Analysis",
        "description": "Model cost impact of moving drugs between tiers",
        "category": CATEGORY_ACTUARIAL,
        "data_source": "claims",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("drug_name", "Drug"),
            _col("current_tier", "Current Tier"),
            _col("proposed_tier", "Proposed Tier"),
            _currency("current_member_cost", "Current Member Cost"),
            _currency("proposed_member_cost", "Proposed Member Cost"),
            _currency("net_plan_impact", "Net Plan Impact"),
        ],
        "required_permission": "actuarial",
        "contains_phi": False,
    },
    {
        "name": "Network Savings Analysis",
        "description": "Compare pharmacy network configurations by cost",
        "category": CATEGORY_ACTUARIAL,
        "data_source": "billing_ap",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("network_config", "Network Config"),
            _int("pharmacy_count", "Pharmacies"),
            _currency("total_paid", "Total Paid"),
            _currency("savings_vs_baseline", "Savings"),
            _col("savings_pct", "Savings %"),
        ],
        "required_permission": "actuarial",
        "contains_phi": False,
    },
    {
        "name": "Rebate Optimization",
        "description": "Model rebate revenue under different formulary strategies",
        "category": CATEGORY_ACTUARIAL,
        "data_source": "journal",
        "default_schedule": FREQ_ON_DEMAND,
        "columns": [
            _col("formulary_strategy", "Strategy"),
            _currency("current_rebates", "Current Rebates"),
            _currency("projected_rebates", "Projected Rebates"),
            _currency("incremental_rebates", "Incremental"),
        ],
        "required_permission": "actuarial",
        "contains_phi": False,
    },
    {
        "name": "Trend Analysis",
        "description": "Historical cost and utilization trends with projections",
        "category": CATEGORY_ACTUARIAL,
        "data_source": "claims",
        "default_schedule": FREQ_QUARTERLY,
        "columns": [
            _col("period", "Period"),
            _int("claim_count", "Claims"),
            _currency("total_cost", "Total Cost"),
            _currency("cost_per_member", "PMPM"),
            _col("trend_pct", "Trend %"),
        ],
        "chart_type": "line",
        "contains_phi": False,
    },
    {
        "name": "Program Benchmarking",
        "description": "Compare program performance vs configurable benchmarks",
        "category": CATEGORY_ACTUARIAL,
        "data_source": "claims",
        "default_schedule": FREQ_QUARTERLY,
        "columns": [
            _col("metric", "Metric"),
            _col("program_value", "Program"),
            _col("benchmark_value", "Benchmark"),
            _col("variance_pct", "Variance %"),
            _col("status", "Status"),
        ],
        "contains_phi": False,
    },
]

PRE_BUILT_DASHBOARDS: list[dict[str, Any]] = [
    {
        "name": "Operator Dashboard",
        "role_target": "operator",
        "is_default": True,
        "layout": [
            {
                "widget_type": "kpi",
                "position": {"x": 0, "y": 0, "w": 3, "h": 2},
                "config": {"report": "Claims Volume Summary", "metric": "claim_count"},
            },
            {
                "widget_type": "kpi",
                "position": {"x": 3, "y": 0, "w": 3, "h": 2},
                "config": {"report": "AP Summary", "metric": "total_amount"},
            },
            {
                "widget_type": "kpi",
                "position": {"x": 6, "y": 0, "w": 3, "h": 2},
                "config": {"report": "Prefund Status", "metric": "days_remaining"},
            },
            {
                "widget_type": "kpi",
                "position": {"x": 9, "y": 0, "w": 3, "h": 2},
                "config": {"report": "FWA Summary Dashboard", "metric": "flag_count"},
            },
            {
                "widget_type": "chart",
                "position": {"x": 0, "y": 2, "w": 8, "h": 4},
                "config": {"report": "Claims Volume Summary", "chart_type": "line"},
            },
            {
                "widget_type": "table",
                "position": {"x": 8, "y": 2, "w": 4, "h": 4},
                "config": {"report": "Settlement Status"},
            },
        ],
    },
    {
        "name": "Client Admin Dashboard",
        "role_target": "client_admin",
        "is_default": True,
        "layout": [
            {
                "widget_type": "kpi",
                "position": {"x": 0, "y": 0, "w": 4, "h": 2},
                "config": {"report": "Claims Volume Summary", "metric": "total_paid"},
            },
            {
                "widget_type": "kpi",
                "position": {"x": 4, "y": 0, "w": 4, "h": 2},
                "config": {"report": "Invoice Summary", "metric": "amount_due"},
            },
            {
                "widget_type": "chart",
                "position": {"x": 0, "y": 2, "w": 12, "h": 4},
                "config": {"report": "Program Financial Summary", "chart_type": "bar"},
            },
        ],
    },
    {
        "name": "Executive Dashboard",
        "role_target": "executive",
        "is_default": True,
        "layout": [
            {
                "widget_type": "kpi",
                "position": {"x": 0, "y": 0, "w": 3, "h": 2},
                "config": {"report": "Revenue by Client", "metric": "total_revenue"},
            },
            {
                "widget_type": "kpi",
                "position": {"x": 3, "y": 0, "w": 3, "h": 2},
                "config": {"report": "Client Profitability", "metric": "profit"},
            },
            {
                "widget_type": "chart",
                "position": {"x": 0, "y": 2, "w": 12, "h": 5},
                "config": {"report": "Cash Flow Report", "chart_type": "bar"},
            },
        ],
    },
    {
        "name": "FWA Analyst Dashboard",
        "role_target": "fwa_analyst",
        "is_default": True,
        "layout": [
            {
                "widget_type": "table",
                "position": {"x": 0, "y": 0, "w": 12, "h": 4},
                "config": {"report": "FWA Summary Dashboard"},
            },
            {
                "widget_type": "chart",
                "position": {"x": 0, "y": 4, "w": 6, "h": 4},
                "config": {"report": "Pharmacy Risk Scorecard", "chart_type": "bar"},
            },
            {
                "widget_type": "table",
                "position": {"x": 6, "y": 4, "w": 6, "h": 4},
                "config": {"report": "Investigation Status"},
            },
        ],
    },
    {
        "name": "Quality Manager Dashboard",
        "role_target": "quality_manager",
        "is_default": True,
        "layout": [
            {
                "widget_type": "chart",
                "position": {"x": 0, "y": 0, "w": 12, "h": 4},
                "config": {"report": "Star Ratings Dashboard", "chart_type": "bar"},
            },
            {
                "widget_type": "table",
                "position": {"x": 0, "y": 4, "w": 12, "h": 4},
                "config": {"report": "PDC Adherence Measures"},
            },
        ],
    },
]


def get_prebuilt_report_count() -> int:
    return len(PREBUILT_REPORTS)


def get_prebuilt_reports_by_category(category: str) -> list[dict[str, Any]]:
    return [r for r in PREBUILT_REPORTS if r["category"] == category]
