"""B9 Tier A batch — 107 FDB tables (simple lookups, generic ingester).

Generated by `modules/drug-database/scripts/gen_fdb_tier_migration.py`
on 2026-05-12. SPEC: charter v3.1 §SPEC-locked migration granularity;
plan v3.1 §W1-W4 tier scope.

Operator: dry-run on a disposable DB before committing (ADVERSARIAL R1 A2):

    alembic upgrade head      # forward
    alembic downgrade -1      # reverse
    alembic upgrade head      # re-apply

All three steps must succeed cleanly. Capture evidence to
`waves/B9/Tier A_dryrun_evidence.md` before committing.

Revision ID: 0009_fdb_tier_a
Revises: 0008_fdb_pricing
Create Date: 2026-05-12
"""
from __future__ import annotations

import os
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision: str = "0009_fdb_tier_a"
down_revision: Union[str, None] = "0008_fdb_pricing"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = "drug_database"

# B7.3 env-driven role pattern — defaults to dev-safe role if env unset.
# Production sets IFX_APP_ROLE=ifx_prod_app explicitly.
_APP_ROLE = os.environ.get("IFX_APP_ROLE", "ifx_dev_app")
_APP_ROLES = ("ifx_dev_app", "ifx_mock_app", _APP_ROLE)


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {_SCHEMA}".format(_SCHEMA=_SCHEMA))

    # RAHFSD1_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RAHFSD1
    op.create_table(
        "rahfsd1_desc",
        sa.Column('AHFS8', sa.Integer(), nullable=False),
        sa.Column('AHFS_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RAPLRT0_APPL_RELATION_TYPE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RAPLRT0
    op.create_table(
        "raplrt0_appl_relation_type",
        sa.Column('APPL_RELATION_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('APPL_RELATION_TYPE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RAPPLTD0_FDA_APPL_TYPE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RAPPLTD0
    op.create_table(
        "rappltd0_fda_appl_type",
        sa.Column('APPL_TYPE_CD', sa.Integer(), nullable=False),
        sa.Column('APPL_TYPE_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RATCD0_ATC_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RATCD0
    op.create_table(
        "ratcd0_atc_desc",
        sa.Column('ATC', sa.Text(), nullable=False),
        sa.Column('ATC_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RBLANG0_NAME_GRP_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RBLANG0
    op.create_table(
        "rblang0_name_grp_desc",
        sa.Column('BIOLOGIC_NAME_GROUPER_ID', sa.Integer(), nullable=False),
        sa.Column('BIOLOGIC_NAME_GROUPER_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RBLASG0_SUBSTANCE_GRP_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RBLASG0
    op.create_table(
        "rblasg0_substance_grp_desc",
        sa.Column('SUBSTANCE_GROUP_ID', sa.Integer(), nullable=False),
        sa.Column('SUBSTANCE_GROUP_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RDCCD0_DRUG_CAT_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RDCCD0
    op.create_table(
        "rdccd0_drug_cat_desc",
        sa.Column('DCC', sa.Text(), nullable=False),
        sa.Column('DCC_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RETCCTD0_ETC_CHANGE_TYPE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RETCCTD0
    op.create_table(
        "retcctd0_etc_change_type_desc",
        sa.Column('ETC_CHANGE_TYPE_CODE', sa.Text(), nullable=False),
        sa.Column('ETC_CHANGE_TYPE_CODE_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RGTCD0_GEN_THERAP_CLASS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RGTCD0
    op.create_table(
        "rgtcd0_gen_therap_class_desc",
        sa.Column('GTC', sa.Integer(), nullable=False),
        sa.Column('GTC_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RHICSCD0_ING_STAT_CD_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RHICSCD0
    op.create_table(
        "rhicscd0_ing_stat_cd_desc",
        sa.Column('ING_STATUS_CD', sa.Integer(), nullable=False),
        sa.Column('ING_STATUS_CD_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RMEDCD0_MED_CONCEPT_TYP_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMEDCD0
    op.create_table(
        "rmedcd0_med_concept_typ_desc",
        sa.Column('MED_CONCEPT_ID_TYP', sa.Integer(), nullable=False),
        sa.Column('MED_CONCEPT_ID_TYP_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RMEDMRD0_MOVE_REASON_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMEDMRD0
    op.create_table(
        "rmedmrd0_move_reason_desc",
        sa.Column('MOVE_REASON_CD', sa.Integer(), nullable=False),
        sa.Column('MOVE_REASON_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RAPLT0_APPL_TYPE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RAPLT0
    op.create_table(
        "raplt0_appl_type",
        sa.Column('APPL_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('APPL_TYPE_ABBREV', sa.Text(), nullable=False),
        sa.Column('APPL_TYPE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RDOSED2_DOSE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RDOSED2
    op.create_table(
        "rdosed2_dose_desc",
        sa.Column('GCDF', sa.Text(), nullable=False),
        sa.Column('DOSE', sa.Text(), nullable=True),
        sa.Column('GCDF_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RHIC1D2_HIC_ORGAN_SYS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RHIC1D2
    op.create_table(
        "rhic1d2_hic_organ_sys_desc",
        sa.Column('HIC1_SEQN', sa.Integer(), nullable=False),
        sa.Column('HIC1', sa.Text(), nullable=False),
        sa.Column('HIC1_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RHIC2D3_HIC_RX_CLASS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RHIC2D3
    op.create_table(
        "rhic2d3_hic_rx_class_desc",
        sa.Column('HIC2_SEQN', sa.Integer(), nullable=False),
        sa.Column('HIC2', sa.Text(), nullable=False),
        sa.Column('HIC2_DESC', sa.Text(), nullable=True),
        sa.Column('HIC2_ROOT', sa.Integer(), nullable=True),
        schema='drug_database',
    )

    # RHIC3D3_HIC_THERAP_CLASS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RHIC3D3
    op.create_table(
        "rhic3d3_hic_therap_class_desc",
        sa.Column('HIC3_SEQN', sa.Integer(), nullable=False),
        sa.Column('HIC3', sa.Text(), nullable=False),
        sa.Column('HIC3_DESC', sa.Text(), nullable=True),
        sa.Column('HIC3_GRPN', sa.Integer(), nullable=True),
        sa.Column('HIC3_ROOT', sa.Integer(), nullable=True),
        schema='drug_database',
    )

    # RLBLRID3_LBLR_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RLBLRID3
    op.create_table(
        "rlblrid3_lblr_desc",
        sa.Column('LBLRID', sa.Text(), nullable=False),
        sa.Column('MFG', sa.Text(), nullable=True),
        sa.Column('LBLRIND', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RMEDSPD0_SPECIFICATION_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMEDSPD0
    op.create_table(
        "rmedspd0_specification_desc",
        sa.Column('MEDID_SPECIFICATION_CODE', sa.Integer(), nullable=False),
        sa.Column('MEDID_SPECIFICATION_CODE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMEDST0_MEDID_SEARCH_TERM — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMEDST0
    op.create_table(
        "rmedst0_medid_search_term",
        sa.Column('MEDID', sa.Integer(), nullable=False),
        sa.Column('SEARCH_TERM_TYPE_CD', sa.Integer(), nullable=False),
        sa.Column('SEARCH_TERM_TEXT', sa.Text(), nullable=False),
        sa.Column('MED_MEDID_DESC', sa.Text(), nullable=False),
        sa.Column('MEDICAL_SUPPLY_IND', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RMEDSTD0_SEARCH_TERM_TYPE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMEDSTD0
    op.create_table(
        "rmedstd0_search_term_type_desc",
        sa.Column('SEARCH_TERM_TYPE_CD', sa.Integer(), nullable=False),
        sa.Column('SEARCH_TERM_TYPE_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIDE2D1_REF_DESI2_IND_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIDE2D1
    op.create_table(
        "rmide2d1_ref_desi2_ind_desc",
        sa.Column('MED_REF_DESI2_IND', sa.Text(), nullable=False),
        sa.Column('MED_REF_DESI2_IND_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIDEAD1_REF_FED_DEA_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIDEAD1
    op.create_table(
        "rmidead1_ref_fed_dea_desc",
        sa.Column('MED_REF_DEA_CD', sa.Text(), nullable=False),
        sa.Column('MED_REF_DEA_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIDESD1_REF_DESI_IND_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIDESD1
    op.create_table(
        "rmidesd1_ref_desi_ind_desc",
        sa.Column('MED_REF_DESI_IND', sa.Text(), nullable=False),
        sa.Column('MED_REF_DESI_IND_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIDFD1_DOSE_FORM — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIDFD1
    op.create_table(
        "rmidfd1_dose_form",
        sa.Column('MED_DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('MED_DOSAGE_FORM_ABBR', sa.Text(), nullable=False),
        sa.Column('MED_DOSAGE_FORM_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIDFID1_ROUTED_DOSE_FORM_MED — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIDFID1
    op.create_table(
        "rmidfid1_routed_dose_form_med",
        sa.Column('ROUTED_DOSAGE_FORM_MED_ID', sa.Integer(), nullable=False),
        sa.Column('ROUTED_MED_ID', sa.Integer(), nullable=False),
        sa.Column('MED_DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('MED_ROUTED_DF_MED_ID_DESC', sa.Text(), nullable=False),
        sa.Column('MED_STATUS_CD', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIGCND1_GCNSEQNO_ASSGN_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIGCND1
    op.create_table(
        "rmigcnd1_gcnseqno_assgn_desc",
        sa.Column('MED_GCNSEQNO_ASSIGN_CD', sa.Text(), nullable=False),
        sa.Column('MED_GCNSEQNO_ASSIGN_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIGECD1_REF_GEN_THERAP_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIGECD1
    op.create_table(
        "rmigecd1_ref_gen_therap_desc",
        sa.Column('MED_REF_GEN_THERA_EQU_CD', sa.Text(), nullable=False),
        sa.Column('MED_REF_GEN_THERA_EQU_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIGNCD1_REF_GEN_NAME_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIGNCD1
    op.create_table(
        "rmigncd1_ref_gen_name_desc",
        sa.Column('MED_REF_GEN_DRUG_NAME_CD', sa.Text(), nullable=False),
        sa.Column('MED_REF_GEN_DRUG_NAME_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIGPCD1_REF_GEN_PRC_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIGPCD1
    op.create_table(
        "rmigpcd1_ref_gen_prc_desc",
        sa.Column('MED_REF_GEN_COMP_PRICE_CD', sa.Text(), nullable=False),
        sa.Column('MED_REF_GEN_COMP_PRICE_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIGSCD1_REF_GEN_PRC_SPRD_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIGSCD1
    op.create_table(
        "rmigscd1_ref_gen_prc_sprd_desc",
        sa.Column('MED_REF_GEN_SPREAD_CD', sa.Text(), nullable=False),
        sa.Column('MED_REF_GEN_SPREAD_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIINND1_REF_INNOV_IND_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIINND1
    op.create_table(
        "rmiinnd1_ref_innov_ind_desc",
        sa.Column('MED_REF_INNOV_IND', sa.Text(), nullable=False),
        sa.Column('MED_REF_INNOV_IND_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMILGND1_REF_FED_LGND_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMILGND1
    op.create_table(
        "rmilgnd1_ref_fed_lgnd_desc",
        sa.Column('MED_REF_FED_LEGEND_IND', sa.Text(), nullable=False),
        sa.Column('MED_REF_FED_LEGEND_IND_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIMLTD1_REF_MULTI_SRC_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIMLTD1
    op.create_table(
        "rmimltd1_ref_multi_src_desc",
        sa.Column('MED_REF_MULTI_SOURCE_CD', sa.Text(), nullable=False),
        sa.Column('MED_REF_MULTI_SOURCE_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMINAMD1_NAME_SRC_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMINAMD1
    op.create_table(
        "rminamd1_name_src_desc",
        sa.Column('MED_NAME_SOURCE_CD', sa.Text(), nullable=False),
        sa.Column('MED_NAME_SOURCE_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMINMD1_MED_NAME_TYPE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMINMD1
    op.create_table(
        "rminmd1_med_name_type_desc",
        sa.Column('MED_NAME_TYPE_CD', sa.Text(), nullable=False),
        sa.Column('MED_NAME_TYPE_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIRMID1_ROUTED_MED — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIRMID1
    op.create_table(
        "rmirmid1_routed_med",
        sa.Column('ROUTED_MED_ID', sa.Integer(), nullable=False),
        sa.Column('MED_NAME_ID', sa.Integer(), nullable=False),
        sa.Column('MED_ROUTE_ID', sa.Integer(), nullable=False),
        sa.Column('MED_ROUTED_MED_ID_DESC', sa.Text(), nullable=False),
        sa.Column('MED_STATUS_CD', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMIRTD1_ROUTE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMIRTD1
    op.create_table(
        "rmirtd1_route",
        sa.Column('MED_ROUTE_ID', sa.Integer(), nullable=False),
        sa.Column('MED_ROUTE_ABBR', sa.Text(), nullable=False),
        sa.Column('MED_ROUTE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMISCD1_STATUS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMISCD1
    op.create_table(
        "rmiscd1_status_desc",
        sa.Column('MED_STATUS_CD', sa.Text(), nullable=False),
        sa.Column('MED_STATUS_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # ROBCD0_OBC_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=ROBCD0
    op.create_table(
        "robcd0_obc_desc",
        sa.Column('OBC', sa.Text(), nullable=False),
        sa.Column('OBC_SN', sa.Integer(), nullable=False),
        sa.Column('OBC_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RPEIAD0_ATTRIBUTE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIAD0
    op.create_table(
        "rpeiad0_attribute_desc",
        sa.Column('ATTRIBUTE_CODE', sa.Integer(), nullable=False),
        sa.Column('ATTRIBUTE_DESC', sa.Text(), nullable=False),
        sa.Column('ATTRIBUTE_TYPE_CODE', sa.Integer(), nullable=False),
        sa.Column('ATTRIBUTE_GROUP_CODE', sa.Integer(), nullable=True),
        schema='drug_database',
    )

    # RPEIAT0_ATTRIBUTE_TYPE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIAT0
    op.create_table(
        "rpeiat0_attribute_type_desc",
        sa.Column('ATTRIBUTE_TYPE_CODE', sa.Integer(), nullable=False),
        sa.Column('ATTRIBUTE_TYPE_DESC', sa.Text(), nullable=False),
        sa.Column('ATTRIBUTE_TYPE_LENGTH', sa.Integer(), nullable=True),
        sa.Column('ATTRIBUTE_TYPE_PRECISION', sa.Integer(), nullable=True),
        schema='drug_database',
    )

    # RPEIAV0_ATTRIBUTE_VALUE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIAV0
    op.create_table(
        "rpeiav0_attribute_value_desc",
        sa.Column('ATTRIBUTE_CODE', sa.Integer(), nullable=False),
        sa.Column('ATTRIBUTE_VALUE', sa.Text(), nullable=False),
        sa.Column('ATTRIBUTE_VALUE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPEIDFA0_DOSAGE_FORM_ATTRIBUTE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIDFA0
    op.create_table(
        "rpeidfa0_dosage_form_attribute",
        sa.Column('DOSAGE_FORM_ATTRIBUTE_ID', sa.Integer(), nullable=False),
        sa.Column('DOSAGE_FORM_ATTRIBUTE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPEIDM0_DOSAGE_FORM_MSTR — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIDM0
    op.create_table(
        "rpeidm0_dosage_form_mstr",
        sa.Column('DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('DOSAGE_FORM_DESC_SHORT', sa.Text(), nullable=True),
        sa.Column('DOSAGE_FORM_DESC_LONG', sa.Text(), nullable=False),
        sa.Column('DOSAGE_FORM_RETIRE_DT', sa.Date(), nullable=True),
        sa.Column('UOM_MSTR_ID', sa.Integer(), nullable=True),
        schema='drug_database',
    )

    # RPEIDT0_DOSAGE_FORM_TYPE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIDT0
    op.create_table(
        "rpeidt0_dosage_form_type",
        sa.Column('DOSAGE_FORM_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('DOSAGE_FORM_TYPE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPEIPP0_PATIENT_PARAM_REQ_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIPP0
    op.create_table(
        "rpeipp0_patient_param_req_desc",
        sa.Column('PATIENT_PARAM_REQ_CD', sa.Integer(), nullable=False),
        sa.Column('PATIENT_PARAM_REQ_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPEIRL0_RT_LABELED_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIRL0
    op.create_table(
        "rpeirl0_rt_labeled_desc",
        sa.Column('RT_LABELED_ID', sa.Integer(), nullable=False),
        sa.Column('RT_LABELED_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPEIST0_STR_CONC_TYPE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIST0
    op.create_table(
        "rpeist0_str_conc_type",
        sa.Column('STR_CONC_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('STR_CONC_TYPE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPEIUT0_UOM_TYPE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIUT0
    op.create_table(
        "rpeiut0_uom_type_desc",
        sa.Column('UOM_TYPE_CD', sa.Integer(), nullable=False),
        sa.Column('UOM_TYPE_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPRDCC0_CURRENCY_CD_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDCC0
    op.create_table(
        "rprdcc0_currency_cd_desc",
        sa.Column('CURRENCY_CD', sa.Text(), nullable=False),
        sa.Column('CURRENCY_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPRDPAD0_PRICE_ATTR_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDPAD0
    op.create_table(
        "rprdpad0_price_attr_desc",
        sa.Column('PRICE_ATTRIBUTE_CD', sa.Text(), nullable=False),
        sa.Column('PRICE_ATTRIBUTE_DESC', sa.Text(), nullable=False),
        sa.Column('PRICE_ATTRIBUTE_TYPE_CD', sa.Text(), nullable=False),
        sa.Column('PRICE_ATTRIBUTE_GROUP_CD', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RNDCTD0_NDC_ATTRIBUTE_TYP_DSC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RNDCTD0
    op.create_table(
        "rndctd0_ndc_attribute_typ_dsc",
        sa.Column('NDC_ATTRIBUTE_TYPE_CD', sa.Integer(), nullable=False),
        sa.Column('NDC_ATTRIBUTE_TYPE_DSC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RNDCVD0_NDC_ATTRIBUTE_VALU_DSC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RNDCVD0
    op.create_table(
        "rndcvd0_ndc_attribute_valu_dsc",
        sa.Column('NDC_ATTRIBUTE_TYPE_CD', sa.Integer(), nullable=False),
        sa.Column('NDC_ATTRIBUTE_VALUE', sa.Text(), nullable=False),
        sa.Column('NDC_ATTRIBUTE_VALUE_DSC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPRDPAT0_PRICE_ATTR_TYPE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDPAT0
    op.create_table(
        "rprdpat0_price_attr_type_desc",
        sa.Column('PRICE_ATTRIBUTE_TYPE_CD', sa.Text(), nullable=False),
        sa.Column('PRICE_ATTRIBUTE_TYPE_DESC', sa.Text(), nullable=False),
        sa.Column('PRICE_ATTRIBUTE_TYPE_LENGTH', sa.Integer(), nullable=True),
        sa.Column('PRICE_ATTRIBUTE_TYPE_PRECISION', sa.Integer(), nullable=True),
        schema='drug_database',
    )

    # RPRDPAV0_PRICE_ATTR_VALUE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDPAV0
    op.create_table(
        "rprdpav0_price_attr_value_desc",
        sa.Column('PRICE_ATTRIBUTE_CD', sa.Text(), nullable=False),
        sa.Column('PRICE_ATTRIBUTE_VALUE', sa.Text(), nullable=False),
        sa.Column('PRICE_ATTRIBUTE_VALUE_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RPRDPCD0_EXT_PRODUCT_CD_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDPCD0
    op.create_table(
        "rprdpcd0_ext_product_cd_desc",
        sa.Column('EXT_PRODUCT_CD_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('EXT_PRODUCT_CD_DESC', sa.Text(), nullable=False),
        sa.Column('EXT_PRODUCT_CD_DATA_TYPE', sa.Text(), nullable=False),
        sa.Column('EXT_PRODUCT_CD_FIELD_LENGTH', sa.Integer(), nullable=False),
        sa.Column('EXT_PRODUCT_CD_DEFINITION', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RPRDPKD0_PACKAGE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDPKD0
    op.create_table(
        "rprdpkd0_package_desc",
        sa.Column('PACKAGE_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('PKG_TYPE_LONG_DESC', sa.Text(), nullable=False),
        sa.Column('PKG_TYPE_SHORT_DESC', sa.Text(), nullable=False),
        sa.Column('ACTIVELY_USED_IND', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RPRDSD0_PRODUCT_STATUS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDSD0
    op.create_table(
        "rprdsd0_product_status_desc",
        sa.Column('FDB_PRODUCT_STATUS_CD', sa.Text(), nullable=False),
        sa.Column('FDB_PRODUCT_STATUS_DESC', sa.Text(), nullable=False),
        sa.Column('FDB_PRODUCT_STATUS_DEFINITION', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RPRDUOM0_PRICE_QTY_UOM — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDUOM0
    op.create_table(
        "rprduom0_price_qty_uom",
        sa.Column('PRICE_UOM_ID', sa.Integer(), nullable=False),
        sa.Column('PRICE_UOM_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RROUTED3_ROUTE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RROUTED3
    op.create_table(
        "rrouted3_route_desc",
        sa.Column('GCRT', sa.Text(), nullable=False),
        sa.Column('RT', sa.Text(), nullable=True),
        sa.Column('GCRT2', sa.Text(), nullable=True),
        sa.Column('GCRT_DESC', sa.Text(), nullable=True),
        sa.Column('SYSTEMIC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RRTGN0_ROUTED_GEN_MSTR — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RRTGN0
    op.create_table(
        "rrtgn0_routed_gen_mstr",
        sa.Column('ROUTED_GEN_ID', sa.Integer(), nullable=False),
        sa.Column('ROUTED_GEN_DESC', sa.Text(), nullable=False),
        sa.Column('GCRT', sa.Text(), nullable=False),
        sa.Column('HICL_SEQNO', sa.Integer(), nullable=False),
        sa.Column('ROUTED_GEN_STATUS_CD', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RRTGNSD0_RTD_GEN_STATUS_DSC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RRTGNSD0
    op.create_table(
        "rrtgnsd0_rtd_gen_status_dsc",
        sa.Column('ROUTED_GEN_STATUS_CD', sa.Text(), nullable=False),
        sa.Column('ROUTED_GEN_STATUS_CD_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RSTR1_STRNGTH_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RSTR1
    op.create_table(
        "rstr1_strngth_desc",
        sa.Column('STR60', sa.Text(), nullable=False),
        sa.Column('STRNUM', sa.Integer(), nullable=True),
        sa.Column('VOLNUM', sa.Integer(), nullable=True),
        sa.Column('STRUN50', sa.Text(), nullable=True),
        sa.Column('VOLUN50', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RSTRSCD0_STRENGTH_STATUS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RSTRSCD0
    op.create_table(
        "rstrscd0_strength_status_desc",
        sa.Column('STRENGTH_STATUS_CODE', sa.Integer(), nullable=False),
        sa.Column('STRENGTH_STATUS_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RSTRTD0_STRENGTH_TYP_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RSTRTD0
    op.create_table(
        "rstrtd0_strength_typ_desc",
        sa.Column('STRENGTH_TYP_CODE', sa.Integer(), nullable=False),
        sa.Column('STRENGTH_TYP_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RSTRUOM0_STRENGTH_UOM — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RSTRUOM0
    op.create_table(
        "rstruom0_strength_uom",
        sa.Column('UOM_ID', sa.Integer(), nullable=False),
        sa.Column('UOM_DESC', sa.Text(), nullable=True),
        sa.Column('UOM_ABBR', sa.Text(), nullable=True),
        sa.Column('UOM_PREFERRED_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RTCD0_STD_THERAP_CLASS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTCD0
    op.create_table(
        "rtcd0_std_therap_class_desc",
        sa.Column('TC', sa.Integer(), nullable=False),
        sa.Column('TC_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RTMDT0_TM_NAME_TYPE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMDT0
    op.create_table(
        "rtmdt0_tm_name_type",
        sa.Column('TM_NAME_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_NAME_TYPE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RTMGRPD1_TM_GROUP_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMGRPD1
    op.create_table(
        "rtmgrpd1_tm_group_desc",
        sa.Column('TM_GROUP_ID', sa.Integer(), nullable=False),
        sa.Column('TM_GROUP_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RTMNGT0_TM_GNN_TYPE — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMNGT0
    op.create_table(
        "rtmngt0_tm_gnn_type",
        sa.Column('TM_GNN_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_GNN_TYPE_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RTMSRCD1_TM_SOURCE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMSRCD1
    op.create_table(
        "rtmsrcd1_tm_source_desc",
        sa.Column('TM_SOURCE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_SOURCE_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RTMDFID1_TM_ROUTED_DF_MED — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMDFID1
    op.create_table(
        "rtmdfid1_tm_routed_df_med",
        sa.Column('ROUTED_DOSAGE_FORM_MED_ID', sa.Integer(), nullable=False),
        sa.Column('TM_SOURCE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_IND', sa.Text(), nullable=False),
        sa.Column('TM_ALT_ROUTED_DF_MED_ID_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RTMMID1_TM_MED — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMMID1
    op.create_table(
        "rtmmid1_tm_med",
        sa.Column('MEDID', sa.Integer(), nullable=False),
        sa.Column('TM_SOURCE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_IND', sa.Text(), nullable=False),
        sa.Column('TM_ALT_MEDID_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RTMNGN0_TM_GNN — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMNGN0
    op.create_table(
        "rtmngn0_tm_gnn",
        sa.Column('HICL_SEQNO', sa.Integer(), nullable=False),
        sa.Column('TM_GNN_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_SOURCE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_IND', sa.Text(), nullable=False),
        sa.Column('TM_ALT_GNN_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RTMNMID1_TM_MED_NAME — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMNMID1
    op.create_table(
        "rtmnmid1_tm_med_name",
        sa.Column('MED_NAME_ID', sa.Integer(), nullable=False),
        sa.Column('TM_SOURCE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_IND', sa.Text(), nullable=False),
        sa.Column('TM_ALT_MED_NAME_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RTMRMID1_TM_ROUTED_MED — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RTMRMID1
    op.create_table(
        "rtmrmid1_tm_routed_med",
        sa.Column('ROUTED_MED_ID', sa.Integer(), nullable=False),
        sa.Column('TM_SOURCE_ID', sa.Integer(), nullable=False),
        sa.Column('TM_IND', sa.Text(), nullable=False),
        sa.Column('TM_ALT_ROUTED_MED_ID_DESC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RETCHCH0_ETC_HICSEQN_HIST — tier=A delta=APPEND_ONLY record_counts_key=RETCHCH0
    op.create_table(
        "retchch0_etc_hicseqn_hist",
        sa.Column('HIC_SEQN', sa.Integer(), nullable=False),
        sa.Column('ETC_ID', sa.Integer(), nullable=False),
        sa.Column('ETC_REVISION_SEQNO', sa.Integer(), nullable=False),
        sa.Column('ETC_CHANGE_TYPE_CODE', sa.Text(), nullable=True),
        sa.Column('ETC_EFFECTIVE_DATE', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RETCHLH0_ETC_HICLSEQNO_HIST — tier=A delta=APPEND_ONLY record_counts_key=RETCHLH0
    op.create_table(
        "retchlh0_etc_hiclseqno_hist",
        sa.Column('HICL_SEQNO', sa.Integer(), nullable=False),
        sa.Column('ETC_ID', sa.Integer(), nullable=False),
        sa.Column('ETC_REVISION_SEQNO', sa.Integer(), nullable=False),
        sa.Column('ETC_CHANGE_TYPE_CODE', sa.Text(), nullable=True),
        sa.Column('ETC_EFFECTIVE_DATE', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RETCNMH0_ETC_MED_NAME_ID_HIST — tier=A delta=APPEND_ONLY record_counts_key=RETCNMH0
    op.create_table(
        "retcnmh0_etc_med_name_id_hist",
        sa.Column('MED_NAME_ID', sa.Integer(), nullable=False),
        sa.Column('ETC_ID', sa.Integer(), nullable=False),
        sa.Column('ETC_REVISION_SEQNO', sa.Integer(), nullable=False),
        sa.Column('ETC_CHANGE_TYPE_CODE', sa.Text(), nullable=True),
        sa.Column('ETC_EFFECTIVE_DATE', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RHICRH0_ING_HIST — tier=A delta=APPEND_ONLY record_counts_key=RHICRH0
    op.create_table(
        "rhicrh0_ing_hist",
        sa.Column('REPL_HIC_SEQN', sa.Integer(), nullable=False),
        sa.Column('PREV_HIC_SEQN', sa.Integer(), nullable=False),
        sa.Column('HIC_REPL_EFF_DT', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RMIDFRH1_ROUTED_DOSE_FORM_HIST — tier=A delta=APPEND_ONLY record_counts_key=RMIDFRH1
    op.create_table(
        "rmidfrh1_routed_dose_form_hist",
        sa.Column('MED_REPL_ROUTED_DF_MED_ID', sa.Integer(), nullable=False),
        sa.Column('MED_PREV_ROUTED_DF_MED_ID', sa.Integer(), nullable=False),
        sa.Column('MED_ROUTED_DF_MED_ID_REP_EF_DT', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RMINMRH1_MED_NAME_HIST — tier=A delta=APPEND_ONLY record_counts_key=RMINMRH1
    op.create_table(
        "rminmrh1_med_name_hist",
        sa.Column('MED_REPL_NAME_ID', sa.Integer(), nullable=False),
        sa.Column('MED_PREV_NAME_ID', sa.Integer(), nullable=False),
        sa.Column('MED_NAME_ID_REPL_EFF_DT', sa.Date(), nullable=False),
        schema='drug_database',
    )

    # RMIRH1_MED_HIST — tier=A delta=APPEND_ONLY record_counts_key=RMIRH1
    op.create_table(
        "rmirh1_med_hist",
        sa.Column('MED_REPL_MEDID', sa.Integer(), nullable=False),
        sa.Column('MED_PREV_MEDID', sa.Integer(), nullable=False),
        sa.Column('MED_MEDID_REPL_EFF_DT', sa.Date(), nullable=False),
        schema='drug_database',
    )

    # RMIRMRH1_ROUTED_MED_HIST — tier=A delta=APPEND_ONLY record_counts_key=RMIRMRH1
    op.create_table(
        "rmirmrh1_routed_med_hist",
        sa.Column('MED_REPL_ROUTED_MED_ID', sa.Integer(), nullable=False),
        sa.Column('MED_PREV_ROUTED_MED_ID', sa.Integer(), nullable=False),
        sa.Column('MED_ROUTED_MED_ID_REPL_EFF_DT', sa.Date(), nullable=False),
        schema='drug_database',
    )

    # RETCSCH0_ETC_SEARCH — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RETCSCH0
    op.create_table(
        "retcsch0_etc_search",
        sa.Column('ETC_SEARCH_ETC_ID', sa.Integer(), nullable=False),
        sa.Column('ETC_PRODUCT_RELATED_ETC_ID', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RETCXRF0_ETC_HIC3_ETC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RETCXRF0
    op.create_table(
        "retcxrf0_etc_hic3_etc",
        sa.Column('ETC_ID', sa.Integer(), nullable=False),
        sa.Column('HIC3_SEQN', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RPEIAL0_DF_ATTRIBUTE_LINK — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIAL0
    op.create_table(
        "rpeial0_df_attribute_link",
        sa.Column('DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('DOSAGE_FORM_ATTRIBUTE_ID', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RPEIGL0_GEN_DF_MSTR_LINK — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIGL0
    op.create_table(
        "rpeigl0_gen_df_mstr_link",
        sa.Column('DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('GCDF', sa.Text(), nullable=False),
        sa.Column('PREFERRED_DOSAGE_FORM_IND', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RPEIML0_MED_DF_MSTR_LINK — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIML0
    op.create_table(
        "rpeiml0_med_df_mstr_link",
        sa.Column('DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('MED_DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('PREFERRED_DOSAGE_FORM_IND', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RPEIOL0_OVW_DF_MSTR_LINK — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIOL0
    op.create_table(
        "rpeiol0_ovw_df_mstr_link",
        sa.Column('DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('OVW_DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('PREFERRED_DOSAGE_FORM_IND', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RPEIRER0_RELATED_RT — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIRER0
    op.create_table(
        "rpeirer0_related_rt",
        sa.Column('CONTINUOUS_RT_ID', sa.Integer(), nullable=False),
        sa.Column('INTERMITTENT_RT_ID', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RPEIRH0_RT_HIERARCHY — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIRH0
    op.create_table(
        "rpeirh0_rt_hierarchy",
        sa.Column('PARENT_RT_ID', sa.Integer(), nullable=False),
        sa.Column('CLINICAL_RT_ID', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RPEIUC0_UOM_CONVERSION — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPEIUC0
    op.create_table(
        "rpeiuc0_uom_conversion",
        sa.Column('FROM_UOM_MSTR_ID', sa.Integer(), nullable=False),
        sa.Column('TO_UOM_MSTR_ID', sa.Integer(), nullable=False),
        sa.Column('UOM_CONVERSION_FACTOR', sa.Numeric(16, 5), nullable=False),
        schema='drug_database',
    )

    # RUNITSD0_UNITS_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RUNITSD0
    op.create_table(
        "runitsd0_units_desc",
        sa.Column('DOSING_MODULE_UNIT_ABBREV', sa.Text(), nullable=False),
        sa.Column('UNIT_DESC_ABBREV', sa.Text(), nullable=True),
        sa.Column('UNIT_DESC_EXPANDED', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RXRNSRC0_SOURCE_DESC — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RXRNSRC0
    op.create_table(
        "rxrnsrc0_source_desc",
        sa.Column('XRF_SOURCE_ID', sa.Integer(), nullable=False),
        sa.Column('XRF_SOURCE_DESC', sa.Text(), nullable=True),
        schema='drug_database',
    )

    # RBLAHIC0_INGREDIENTS — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RBLAHIC0
    op.create_table(
        "rblahic0_ingredients",
        sa.Column('BLA_APPL_NBR', sa.Text(), nullable=False),
        sa.Column('APPL_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('BIOLOGICS_SN', sa.Integer(), nullable=False),
        sa.Column('MULTI_INGREDIENT_SN', sa.Integer(), nullable=False),
        sa.Column('HIC_SEQN', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RBLAPN0_PROPRIETARY_NAME — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RBLAPN0
    op.create_table(
        "rblapn0_proprietary_name",
        sa.Column('PROPRIETARY_NAME_ID', sa.Integer(), nullable=False),
        sa.Column('BLA_APPL_NBR', sa.Text(), nullable=False),
        sa.Column('APPL_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('PROPRIETARY_NAME', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RMEDMGL0_MED_GENERIC_MED_LINK — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMEDMGL0
    op.create_table(
        "rmedmgl0_med_generic_med_link",
        sa.Column('MED_CONCEPT_ID', sa.Integer(), nullable=False),
        sa.Column('MED_CONCEPT_ID_TYP', sa.Integer(), nullable=False),
        sa.Column('GENERIC_MED_CONCEPT_ID', sa.Integer(), nullable=False),
        sa.Column('MED_CONCEPT_OBSDATEC', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RMEDMHL0_MED_HICLSEQNO_LINK — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RMEDMHL0
    op.create_table(
        "rmedmhl0_med_hiclseqno_link",
        sa.Column('MED_CONCEPT_ID', sa.Integer(), nullable=False),
        sa.Column('MED_CONCEPT_ID_TYP', sa.Integer(), nullable=False),
        sa.Column('HICL_SEQNO', sa.Integer(), nullable=False),
        sa.Column('MED_CONCEPT_HICL_SRC_CD', sa.Integer(), nullable=False),
        sa.Column('MED_CONCEPT_OBSDATEC', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RPRDPC0_EXT_PRODUCT_CD — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RPRDPC0
    op.create_table(
        "rprdpc0_ext_product_cd",
        sa.Column('FDB_PRODUCT_ID', sa.Integer(), nullable=False),
        sa.Column('EXT_PRODUCT_CD_TYPE_ID', sa.Integer(), nullable=False),
        sa.Column('EXT_PRODUCT_CD_START_DT', sa.Date(), nullable=False),
        sa.Column('EXT_PRODUCT_CD', sa.Text(), nullable=False),
        sa.Column('EXT_PRODUCT_CD_END_DT', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RXRFAHX0_AGCSP_HICSEQN — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RXRFAHX0
    op.create_table(
        "rxrfahx0_agcsp_hicseqn",
        sa.Column('DAM_AGCSP', sa.Integer(), nullable=False),
        sa.Column('HIC_SEQN', sa.Integer(), nullable=False),
        sa.Column('HIC', sa.Text(), nullable=False),
        schema='drug_database',
    )

    # RXRFDDX0_DACN_AGCSP — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RXRFDDX0
    op.create_table(
        "rxrfddx0_dacn_agcsp",
        sa.Column('DACN', sa.Text(), nullable=False),
        sa.Column('DAM_AGCSP', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RXRGDFQ0_GCDF_SCRIPT_QQ — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RXRGDFQ0
    op.create_table(
        "rxrgdfq0_gcdf_script_qq",
        sa.Column('GCDF', sa.Text(), nullable=False),
        sa.Column('SCRIPT_QQ_ID', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RXRMDFQ0_MEDDOSFM_SCRIPT_QQ — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RXRMDFQ0
    op.create_table(
        "rxrmdfq0_meddosfm_script_qq",
        sa.Column('MED_DOSAGE_FORM_ID', sa.Integer(), nullable=False),
        sa.Column('SCRIPT_QQ_ID', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    # RXRNCQQ0_QQ_MSTR — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RXRNCQQ0
    op.create_table(
        "rxrncqq0_qq_mstr",
        sa.Column('SCRIPT_QQ_ID', sa.Integer(), nullable=False),
        sa.Column('SCRIPT_QQ_CD', sa.Text(), nullable=True),
        sa.Column('SCRIPT_QQ_DESC', sa.Text(), nullable=True),
        sa.Column('XRF_SOURCE_ID', sa.Integer(), nullable=True),
        sa.Column('OBSOLETE_DATE', sa.Date(), nullable=True),
        schema='drug_database',
    )

    # RXRPDFQ0_POEMDOSFM_SCRIPT_QQ — tier=A delta=UPSERT_BY_NATURAL_KEY record_counts_key=RXRPDFQ0
    op.create_table(
        "rxrpdfq0_poemdosfm_script_qq",
        sa.Column('POEUNITCDE', sa.Integer(), nullable=False),
        sa.Column('SCRIPT_QQ_ID', sa.Integer(), nullable=False),
        schema='drug_database',
    )

    for _table in (
        "rahfsd1_desc",
        "raplrt0_appl_relation_type",
        "rappltd0_fda_appl_type",
        "ratcd0_atc_desc",
        "rblang0_name_grp_desc",
        "rblasg0_substance_grp_desc",
        "rdccd0_drug_cat_desc",
        "retcctd0_etc_change_type_desc",
        "rgtcd0_gen_therap_class_desc",
        "rhicscd0_ing_stat_cd_desc",
        "rmedcd0_med_concept_typ_desc",
        "rmedmrd0_move_reason_desc",
        "raplt0_appl_type",
        "rdosed2_dose_desc",
        "rhic1d2_hic_organ_sys_desc",
        "rhic2d3_hic_rx_class_desc",
        "rhic3d3_hic_therap_class_desc",
        "rlblrid3_lblr_desc",
        "rmedspd0_specification_desc",
        "rmedst0_medid_search_term",
        "rmedstd0_search_term_type_desc",
        "rmide2d1_ref_desi2_ind_desc",
        "rmidead1_ref_fed_dea_desc",
        "rmidesd1_ref_desi_ind_desc",
        "rmidfd1_dose_form",
        "rmidfid1_routed_dose_form_med",
        "rmigcnd1_gcnseqno_assgn_desc",
        "rmigecd1_ref_gen_therap_desc",
        "rmigncd1_ref_gen_name_desc",
        "rmigpcd1_ref_gen_prc_desc",
        "rmigscd1_ref_gen_prc_sprd_desc",
        "rmiinnd1_ref_innov_ind_desc",
        "rmilgnd1_ref_fed_lgnd_desc",
        "rmimltd1_ref_multi_src_desc",
        "rminamd1_name_src_desc",
        "rminmd1_med_name_type_desc",
        "rmirmid1_routed_med",
        "rmirtd1_route",
        "rmiscd1_status_desc",
        "robcd0_obc_desc",
        "rpeiad0_attribute_desc",
        "rpeiat0_attribute_type_desc",
        "rpeiav0_attribute_value_desc",
        "rpeidfa0_dosage_form_attribute",
        "rpeidm0_dosage_form_mstr",
        "rpeidt0_dosage_form_type",
        "rpeipp0_patient_param_req_desc",
        "rpeirl0_rt_labeled_desc",
        "rpeist0_str_conc_type",
        "rpeiut0_uom_type_desc",
        "rprdcc0_currency_cd_desc",
        "rprdpad0_price_attr_desc",
        "rndctd0_ndc_attribute_typ_dsc",
        "rndcvd0_ndc_attribute_valu_dsc",
        "rprdpat0_price_attr_type_desc",
        "rprdpav0_price_attr_value_desc",
        "rprdpcd0_ext_product_cd_desc",
        "rprdpkd0_package_desc",
        "rprdsd0_product_status_desc",
        "rprduom0_price_qty_uom",
        "rrouted3_route_desc",
        "rrtgn0_routed_gen_mstr",
        "rrtgnsd0_rtd_gen_status_dsc",
        "rstr1_strngth_desc",
        "rstrscd0_strength_status_desc",
        "rstrtd0_strength_typ_desc",
        "rstruom0_strength_uom",
        "rtcd0_std_therap_class_desc",
        "rtmdt0_tm_name_type",
        "rtmgrpd1_tm_group_desc",
        "rtmngt0_tm_gnn_type",
        "rtmsrcd1_tm_source_desc",
        "rtmdfid1_tm_routed_df_med",
        "rtmmid1_tm_med",
        "rtmngn0_tm_gnn",
        "rtmnmid1_tm_med_name",
        "rtmrmid1_tm_routed_med",
        "retchch0_etc_hicseqn_hist",
        "retchlh0_etc_hiclseqno_hist",
        "retcnmh0_etc_med_name_id_hist",
        "rhicrh0_ing_hist",
        "rmidfrh1_routed_dose_form_hist",
        "rminmrh1_med_name_hist",
        "rmirh1_med_hist",
        "rmirmrh1_routed_med_hist",
        "retcsch0_etc_search",
        "retcxrf0_etc_hic3_etc",
        "rpeial0_df_attribute_link",
        "rpeigl0_gen_df_mstr_link",
        "rpeiml0_med_df_mstr_link",
        "rpeiol0_ovw_df_mstr_link",
        "rpeirer0_related_rt",
        "rpeirh0_rt_hierarchy",
        "rpeiuc0_uom_conversion",
        "runitsd0_units_desc",
        "rxrnsrc0_source_desc",
        "rblahic0_ingredients",
        "rblapn0_proprietary_name",
        "rmedmgl0_med_generic_med_link",
        "rmedmhl0_med_hiclseqno_link",
        "rprdpc0_ext_product_cd",
        "rxrfahx0_agcsp_hicseqn",
        "rxrfddx0_dacn_agcsp",
        "rxrgdfq0_gcdf_script_qq",
        "rxrmdfq0_meddosfm_script_qq",
        "rxrncqq0_qq_mstr",
        "rxrpdfq0_poemdosfm_script_qq",
    ):
        for _role in _APP_ROLES:
            op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {_SCHEMA}.{_table} TO {_role}")


def downgrade() -> None:
    op.drop_table("rxrpdfq0_poemdosfm_script_qq", schema=_SCHEMA)
    op.drop_table("rxrncqq0_qq_mstr", schema=_SCHEMA)
    op.drop_table("rxrmdfq0_meddosfm_script_qq", schema=_SCHEMA)
    op.drop_table("rxrgdfq0_gcdf_script_qq", schema=_SCHEMA)
    op.drop_table("rxrfddx0_dacn_agcsp", schema=_SCHEMA)
    op.drop_table("rxrfahx0_agcsp_hicseqn", schema=_SCHEMA)
    op.drop_table("rprdpc0_ext_product_cd", schema=_SCHEMA)
    op.drop_table("rmedmhl0_med_hiclseqno_link", schema=_SCHEMA)
    op.drop_table("rmedmgl0_med_generic_med_link", schema=_SCHEMA)
    op.drop_table("rblapn0_proprietary_name", schema=_SCHEMA)
    op.drop_table("rblahic0_ingredients", schema=_SCHEMA)
    op.drop_table("rxrnsrc0_source_desc", schema=_SCHEMA)
    op.drop_table("runitsd0_units_desc", schema=_SCHEMA)
    op.drop_table("rpeiuc0_uom_conversion", schema=_SCHEMA)
    op.drop_table("rpeirh0_rt_hierarchy", schema=_SCHEMA)
    op.drop_table("rpeirer0_related_rt", schema=_SCHEMA)
    op.drop_table("rpeiol0_ovw_df_mstr_link", schema=_SCHEMA)
    op.drop_table("rpeiml0_med_df_mstr_link", schema=_SCHEMA)
    op.drop_table("rpeigl0_gen_df_mstr_link", schema=_SCHEMA)
    op.drop_table("rpeial0_df_attribute_link", schema=_SCHEMA)
    op.drop_table("retcxrf0_etc_hic3_etc", schema=_SCHEMA)
    op.drop_table("retcsch0_etc_search", schema=_SCHEMA)
    op.drop_table("rmirmrh1_routed_med_hist", schema=_SCHEMA)
    op.drop_table("rmirh1_med_hist", schema=_SCHEMA)
    op.drop_table("rminmrh1_med_name_hist", schema=_SCHEMA)
    op.drop_table("rmidfrh1_routed_dose_form_hist", schema=_SCHEMA)
    op.drop_table("rhicrh0_ing_hist", schema=_SCHEMA)
    op.drop_table("retcnmh0_etc_med_name_id_hist", schema=_SCHEMA)
    op.drop_table("retchlh0_etc_hiclseqno_hist", schema=_SCHEMA)
    op.drop_table("retchch0_etc_hicseqn_hist", schema=_SCHEMA)
    op.drop_table("rtmrmid1_tm_routed_med", schema=_SCHEMA)
    op.drop_table("rtmnmid1_tm_med_name", schema=_SCHEMA)
    op.drop_table("rtmngn0_tm_gnn", schema=_SCHEMA)
    op.drop_table("rtmmid1_tm_med", schema=_SCHEMA)
    op.drop_table("rtmdfid1_tm_routed_df_med", schema=_SCHEMA)
    op.drop_table("rtmsrcd1_tm_source_desc", schema=_SCHEMA)
    op.drop_table("rtmngt0_tm_gnn_type", schema=_SCHEMA)
    op.drop_table("rtmgrpd1_tm_group_desc", schema=_SCHEMA)
    op.drop_table("rtmdt0_tm_name_type", schema=_SCHEMA)
    op.drop_table("rtcd0_std_therap_class_desc", schema=_SCHEMA)
    op.drop_table("rstruom0_strength_uom", schema=_SCHEMA)
    op.drop_table("rstrtd0_strength_typ_desc", schema=_SCHEMA)
    op.drop_table("rstrscd0_strength_status_desc", schema=_SCHEMA)
    op.drop_table("rstr1_strngth_desc", schema=_SCHEMA)
    op.drop_table("rrtgnsd0_rtd_gen_status_dsc", schema=_SCHEMA)
    op.drop_table("rrtgn0_routed_gen_mstr", schema=_SCHEMA)
    op.drop_table("rrouted3_route_desc", schema=_SCHEMA)
    op.drop_table("rprduom0_price_qty_uom", schema=_SCHEMA)
    op.drop_table("rprdsd0_product_status_desc", schema=_SCHEMA)
    op.drop_table("rprdpkd0_package_desc", schema=_SCHEMA)
    op.drop_table("rprdpcd0_ext_product_cd_desc", schema=_SCHEMA)
    op.drop_table("rprdpav0_price_attr_value_desc", schema=_SCHEMA)
    op.drop_table("rprdpat0_price_attr_type_desc", schema=_SCHEMA)
    op.drop_table("rndcvd0_ndc_attribute_valu_dsc", schema=_SCHEMA)
    op.drop_table("rndctd0_ndc_attribute_typ_dsc", schema=_SCHEMA)
    op.drop_table("rprdpad0_price_attr_desc", schema=_SCHEMA)
    op.drop_table("rprdcc0_currency_cd_desc", schema=_SCHEMA)
    op.drop_table("rpeiut0_uom_type_desc", schema=_SCHEMA)
    op.drop_table("rpeist0_str_conc_type", schema=_SCHEMA)
    op.drop_table("rpeirl0_rt_labeled_desc", schema=_SCHEMA)
    op.drop_table("rpeipp0_patient_param_req_desc", schema=_SCHEMA)
    op.drop_table("rpeidt0_dosage_form_type", schema=_SCHEMA)
    op.drop_table("rpeidm0_dosage_form_mstr", schema=_SCHEMA)
    op.drop_table("rpeidfa0_dosage_form_attribute", schema=_SCHEMA)
    op.drop_table("rpeiav0_attribute_value_desc", schema=_SCHEMA)
    op.drop_table("rpeiat0_attribute_type_desc", schema=_SCHEMA)
    op.drop_table("rpeiad0_attribute_desc", schema=_SCHEMA)
    op.drop_table("robcd0_obc_desc", schema=_SCHEMA)
    op.drop_table("rmiscd1_status_desc", schema=_SCHEMA)
    op.drop_table("rmirtd1_route", schema=_SCHEMA)
    op.drop_table("rmirmid1_routed_med", schema=_SCHEMA)
    op.drop_table("rminmd1_med_name_type_desc", schema=_SCHEMA)
    op.drop_table("rminamd1_name_src_desc", schema=_SCHEMA)
    op.drop_table("rmimltd1_ref_multi_src_desc", schema=_SCHEMA)
    op.drop_table("rmilgnd1_ref_fed_lgnd_desc", schema=_SCHEMA)
    op.drop_table("rmiinnd1_ref_innov_ind_desc", schema=_SCHEMA)
    op.drop_table("rmigscd1_ref_gen_prc_sprd_desc", schema=_SCHEMA)
    op.drop_table("rmigpcd1_ref_gen_prc_desc", schema=_SCHEMA)
    op.drop_table("rmigncd1_ref_gen_name_desc", schema=_SCHEMA)
    op.drop_table("rmigecd1_ref_gen_therap_desc", schema=_SCHEMA)
    op.drop_table("rmigcnd1_gcnseqno_assgn_desc", schema=_SCHEMA)
    op.drop_table("rmidfid1_routed_dose_form_med", schema=_SCHEMA)
    op.drop_table("rmidfd1_dose_form", schema=_SCHEMA)
    op.drop_table("rmidesd1_ref_desi_ind_desc", schema=_SCHEMA)
    op.drop_table("rmidead1_ref_fed_dea_desc", schema=_SCHEMA)
    op.drop_table("rmide2d1_ref_desi2_ind_desc", schema=_SCHEMA)
    op.drop_table("rmedstd0_search_term_type_desc", schema=_SCHEMA)
    op.drop_table("rmedst0_medid_search_term", schema=_SCHEMA)
    op.drop_table("rmedspd0_specification_desc", schema=_SCHEMA)
    op.drop_table("rlblrid3_lblr_desc", schema=_SCHEMA)
    op.drop_table("rhic3d3_hic_therap_class_desc", schema=_SCHEMA)
    op.drop_table("rhic2d3_hic_rx_class_desc", schema=_SCHEMA)
    op.drop_table("rhic1d2_hic_organ_sys_desc", schema=_SCHEMA)
    op.drop_table("rdosed2_dose_desc", schema=_SCHEMA)
    op.drop_table("raplt0_appl_type", schema=_SCHEMA)
    op.drop_table("rmedmrd0_move_reason_desc", schema=_SCHEMA)
    op.drop_table("rmedcd0_med_concept_typ_desc", schema=_SCHEMA)
    op.drop_table("rhicscd0_ing_stat_cd_desc", schema=_SCHEMA)
    op.drop_table("rgtcd0_gen_therap_class_desc", schema=_SCHEMA)
    op.drop_table("retcctd0_etc_change_type_desc", schema=_SCHEMA)
    op.drop_table("rdccd0_drug_cat_desc", schema=_SCHEMA)
    op.drop_table("rblasg0_substance_grp_desc", schema=_SCHEMA)
    op.drop_table("rblang0_name_grp_desc", schema=_SCHEMA)
    op.drop_table("ratcd0_atc_desc", schema=_SCHEMA)
    op.drop_table("rappltd0_fda_appl_type", schema=_SCHEMA)
    op.drop_table("raplrt0_appl_relation_type", schema=_SCHEMA)
    op.drop_table("rahfsd1_desc", schema=_SCHEMA)
