"""adjudication_engine RLS tenant isolation.

Applies row-level security policies to all 6 tenant-scoped tables per
the Wave 20 B2 pattern. SQL generated by ``scripts/apply_rls.py
--schema adjudication_engine --dry-run`` and embedded here for
auditability.

Two non-negotiables per Wave 20 B2 finding:
1. ``FORCE ROW LEVEL SECURITY`` (not just ENABLE) — owner-bypass defeats
   plain ENABLE when the tenant role owns the table.
2. ``NULLIF(current_setting('app.current_tenant_id', true), '')::uuid``
   — unset GUCs return empty string, which fails ``::uuid`` cast.

Policy ``tenant_isolation`` is granted to the three tier app roles
(``ifx_dev_app``, ``ifx_mock_app``, ``ifx_prod_app``). Admin roles
(``ifx_<tier>_admin``) have the ``BYPASSRLS`` attribute so policies
don't apply to them — that's where migrations and cross-tenant admin
ops run.

Revision ID: 0003_adj_rls
Revises: 0002_adj_check_constraints
Create Date: 2026-04-21
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0003_adj_rls"
down_revision: Union[str, None] = "0002_adj_check_constraints"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = "adjudication_engine"
_TABLES = (
    "claim_overrides",
    "claim_transactions",
    "copay_fraud_flags",
    "drug_waste_alerts",
    "dur_screening_logs",
    "override_approval_configs",
)
import os
_APP_ROLE = os.environ.get("IFX_APP_ROLE", "ifx_dev_app")
_ROLES = f"ifx_dev_app, ifx_mock_app, {_APP_ROLE}"
_PREDICATE = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    for table in _TABLES:
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {_SCHEMA}.{table}
              FOR ALL
              TO {_ROLES}
              USING      ({_PREDICATE})
              WITH CHECK ({_PREDICATE});
            """
        )


def downgrade() -> None:
    for table in _TABLES:
        op.execute(
            f"DROP POLICY IF EXISTS tenant_isolation ON {_SCHEMA}.{table};"
        )
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} DISABLE ROW LEVEL SECURITY;")
