#!/usr/bin/env python3
"""
Load the synthetic mock claims file into billing.claim_records.

Reads:  data/mock/demo_claims.txt  (pipe-delimited, 63 cols, generated by
        infrastructure/scripts/scramble_claims.py)
        data/mock/client_to_groupid_mappings_demo.csv  (group → company name)

Writes: <DATABASE_URL>.billing.claim_records, scoped to a fixed DEMO_TENANT_ID
        so re-running the loader is idempotent (DELETE-then-INSERT, never
        appends duplicates).

The DATABASE_URL is read from the active environment (.env.mock when
INFINITYRX_ENV=mock). The script REFUSES to load against a database whose
URL contains 'infinityrx_prod' — synthetic claims must never enter prod.

Usage:
  source infrastructure/scripts/switch_env.sh mock
  python infrastructure/scripts/load_demo_claims.py
"""

from __future__ import annotations

import csv
import os
import sys
import uuid
from datetime import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path

import psycopg2
import psycopg2.extras

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from shared.config import get_settings  # noqa: E402

# Fixed demo tenant — every synthetic row gets this tenant_id, so a single
# DELETE WHERE tenant_id = DEMO_TENANT_ID wipes the dataset cleanly.
DEMO_TENANT_ID = uuid.UUID("11111111-1111-1111-1111-111111111111")

# Source files
CLAIMS_PATH = REPO_ROOT / "data" / "mock" / "demo_claims.txt"
MAPPING_PATH = REPO_ROOT / "data" / "mock" / "client_to_groupid_mappings_demo.csv"

# Canonical 63-column schema — same as scramble_claims.py
COLUMNS = [
    "Client Provided Unique ID", "Paid / Reversal Status Code", "BIN", "PCN",
    "Date of Service", "Date Written", "Group Number", "Cardholder ID",
    "LastName", "FirstName", "DOB", "Person Code", "Service Provider ID",
    "NDC", "Rx Number", "Quantity", "Days Supply", "Compound Code", "DAW",
    "Submitted Ingredient Cost", "Submitted Dispensing Fee",
    "Usual and Customary", "Submitted Gross Amount Due", "Submitted Tax",
    "Prescriber NPI", "Copay", "Patient Pay Amount",
    "Amount Applied to Deductible", "Amount Applied to Out of Pocket",
    "Pharmacy Total Paid", "Pharmacy Ingredient Cost Paid",
    "Pharmacy Dispensing Fee Paid", "Pharmacy Tax Paid",
    "Sell Ingredient Cost", "Sell Dispensing Fee", "Sell Tax",
    "Total Client Billed", "Other Coverage Code", "Process Date / Time",
    "Price Source", "Keyed Claim Indicator", "Selfpay Indicator",
    "Is Billable", "Historical", "Test Claim", "Location Code", "ScriptTag",
    "DrugTier", "BrandGeneric", "IsPreferred", "SenderID",
    "Network Reimbursement ID", "Amount Applied to Benefit Cap",
    "Claim Processing Fee", "Transaction Fees", "Reversal Auth Reference",
    "Statement Flag", "Bank Routing Number", "Bank Account Number",
    "Bank Account Type", "Primary Chain Code", "Debit Card Amount",
    "POS Adjustment",
]
COL = {name: idx for idx, name in enumerate(COLUMNS)}

# Per-batch insert size — large enough to amortize round-trips, small enough
# that a single failed batch stays diagnosable.
BATCH_SIZE = 5_000


def _decimal(value: str) -> Decimal:
    if not value:
        return Decimal("0")
    try:
        return Decimal(value)
    except (InvalidOperation, ValueError):
        return Decimal("0")


def _parse_date(value: str):
    if not value:
        return None
    try:
        return datetime.strptime(value, "%m/%d/%Y").date()
    except ValueError:
        return None


def _parse_datetime(value: str):
    if not value:
        return None
    try:
        return datetime.strptime(value, "%m/%d/%Y %H:%M:%S")
    except ValueError:
        try:
            return datetime.strptime(value, "%m/%d/%Y")
        except ValueError:
            return None


def _int(value: str):
    try:
        return int(value) if value else None
    except ValueError:
        return None


def load_group_to_client_map() -> dict[str, str]:
    """Return {group_id: company_name} from the demo mapping CSV."""
    if not MAPPING_PATH.exists():
        return {}
    out: dict[str, str] = {}
    with MAPPING_PATH.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            out[row["Group ID"].strip()] = row["Company"].strip()
    return out


def build_row_tuple(
    fields: list[str],
    group_to_client: dict[str, str],
    now: datetime,
) -> tuple | None:
    """Convert one parsed line to a tuple matching the INSERT column order."""
    auth_number = fields[COL["Client Provided Unique ID"]].strip()
    if not auth_number:
        return None

    pharmacy_npi = fields[COL["Service Provider ID"]].strip()
    if not pharmacy_npi:
        return None

    dos = _parse_date(fields[COL["Date of Service"]])
    if dos is None:
        return None

    date_received = _parse_datetime(fields[COL["Process Date / Time"]]) or now
    status_code = fields[COL["Paid / Reversal Status Code"]].strip() or "P"
    claim_type = "reversal" if status_code.upper() == "R" else "paid"

    group_id = fields[COL["Group Number"]].strip()
    client_name = group_to_client.get(group_id, group_id or "Unknown")

    ndc = fields[COL["NDC"]].strip()[:11] or None
    quantity = _decimal(fields[COL["Quantity"]])
    days_supply = _int(fields[COL["Days Supply"]])

    ingredient_cost = _decimal(fields[COL["Submitted Ingredient Cost"]])
    dispensing_fee = _decimal(fields[COL["Submitted Dispensing Fee"]])
    patient_pay = _decimal(fields[COL["Patient Pay Amount"]])
    plan_pay = _decimal(fields[COL["Pharmacy Total Paid"]])
    other_payer = Decimal("0")
    net_amount = plan_pay  # demo: plan paid = net amount the demo client owes

    return (
        str(uuid.uuid4()),                           # id
        str(DEMO_TENANT_ID),                         # tenant_id
        "demo_synthetic",                            # source_type
        None,                                        # source_file_id
        None,                                        # source_claim_id
        auth_number,                                 # auth_number
        fields[COL["Reversal Auth Reference"]] or None,  # reversal_of_auth
        claim_type,                                  # claim_type
        fields[COL["Cardholder ID"]] or None,        # member_id
        pharmacy_npi,                                # pharmacy_npi
        None,                                        # pharmacy_name
        fields[COL["Prescriber NPI"]] or None,       # prescriber_npi
        ndc,                                         # ndc
        None,                                        # drug_name
        quantity,                                    # quantity
        days_supply,                                 # days_supply
        dos,                                         # date_of_service
        date_received,                               # date_received
        None,                                        # program_id
        None,                                        # program_name
        None,                                        # client_id
        client_name,                                 # client_name
        fields[COL["Network Reimbursement ID"]] or None,  # network_reimbursement_id
        ingredient_cost,                             # ingredient_cost
        dispensing_fee,                              # dispensing_fee
        patient_pay,                                 # patient_pay
        plan_pay,                                    # plan_pay
        other_payer,                                 # other_payer_amount
        net_amount,                                  # net_amount
        Decimal("0"),                                # under_reimbursement
        None,                                        # payment_route
        None,                                        # payment_vendor_config_id
        None,                                        # payment_schedule
        None,                                        # pay_to_entity_id
        None,                                        # pay_to_entity_name
        False,                                       # is_excluded
        None,                                        # exclusion_reason
        False,                                       # is_statement
        "ingested",                                  # status
        now,                                         # created_at
    )


INSERT_COLUMNS = [
    "id", "tenant_id", "source_type", "source_file_id", "source_claim_id",
    "auth_number", "reversal_of_auth", "claim_type", "member_id",
    "pharmacy_npi", "pharmacy_name", "prescriber_npi", "ndc", "drug_name",
    "quantity", "days_supply", "date_of_service", "date_received",
    "program_id", "program_name", "client_id", "client_name",
    "network_reimbursement_id", "ingredient_cost", "dispensing_fee",
    "patient_pay", "plan_pay", "other_payer_amount", "net_amount",
    "under_reimbursement", "payment_route", "payment_vendor_config_id",
    "payment_schedule", "pay_to_entity_id", "pay_to_entity_name",
    "is_excluded", "exclusion_reason", "is_statement", "status", "created_at",
]
INSERT_SQL = (
    "INSERT INTO billing.claim_records ("
    + ", ".join(INSERT_COLUMNS)
    + ") VALUES %s"
)


def main() -> int:
    settings = get_settings()
    db_url = settings.DATABASE_URL.replace("+asyncpg", "+psycopg2")
    if "infinityrx_prod" in db_url:
        print("REFUSING: cannot load synthetic demo claims into prod.", file=sys.stderr)
        print("          Active DATABASE_URL points at infinityrx_prod.", file=sys.stderr)
        return 2
    if "infinityrx_mock" not in db_url and "infinityrx_dev" not in db_url:
        print(f"WARNING: target database is not mock or dev: {db_url}", file=sys.stderr)
        print("         Continuing anyway — confirm INFINITYRX_ENV.", file=sys.stderr)

    if not CLAIMS_PATH.exists():
        print(f"ERROR: not found: {CLAIMS_PATH}", file=sys.stderr)
        return 2

    print(f"[load] target  : {db_url.split('@')[-1]}")
    print(f"[load] source  : {CLAIMS_PATH}")
    print(f"[load] mapping : {MAPPING_PATH}")
    print(f"[load] tenant  : {DEMO_TENANT_ID}")

    group_to_client = load_group_to_client_map()
    print(f"[load] {len(group_to_client)} client mappings loaded")

    # psycopg2 doesn't accept the SQLAlchemy +driver suffix — strip it.
    raw_url = db_url.replace("+psycopg2", "")
    conn = psycopg2.connect(raw_url)
    conn.autocommit = False
    try:
        with conn.cursor() as cur:
            cur.execute(
                "DELETE FROM billing.claim_records WHERE tenant_id = %s",
                (str(DEMO_TENANT_ID),),
            )
            deleted = cur.rowcount
            print(f"[load] deleted {deleted:,} pre-existing demo rows")

        rows_in = 0
        rows_inserted = 0
        rows_skipped = 0
        now = datetime.now()
        batch: list[tuple] = []

        with CLAIMS_PATH.open("r", encoding="utf-8") as src:
            header = src.readline().rstrip("\n").rstrip("\r")
            if header != "|".join(COLUMNS):
                print("ERROR: header does not match canonical schema", file=sys.stderr)
                return 1

            for raw in src:
                line = raw.rstrip("\n").rstrip("\r")
                if not line:
                    continue
                fields = line.split("|")
                rows_in += 1
                if len(fields) != len(COLUMNS):
                    rows_skipped += 1
                    continue
                tup = build_row_tuple(fields, group_to_client, now)
                if tup is None:
                    rows_skipped += 1
                    continue
                batch.append(tup)

                if len(batch) >= BATCH_SIZE:
                    with conn.cursor() as cur:
                        psycopg2.extras.execute_values(cur, INSERT_SQL, batch, page_size=BATCH_SIZE)
                    rows_inserted += len(batch)
                    batch.clear()
                    if rows_inserted % 25_000 == 0:
                        print(f"  ... {rows_inserted:,} inserted")

            if batch:
                with conn.cursor() as cur:
                    psycopg2.extras.execute_values(cur, INSERT_SQL, batch, page_size=BATCH_SIZE)
                rows_inserted += len(batch)

        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    print()
    print(f"[load] rows in       : {rows_in:,}")
    print(f"[load] rows inserted : {rows_inserted:,}")
    print(f"[load] rows skipped  : {rows_skipped:,}")
    print(f"[load] DONE")
    return 0


if __name__ == "__main__":
    sys.exit(main())
