#!/usr/bin/env python3
"""
Generate synthetic claim records for the mock environment.

DESIGN: this is a pure synthetic generator — it does NOT read real PHI from
anywhere. Every field (member name, DOB, cardholder ID, banking, NPIs, claim
identifiers, amounts, dates) is either generated by Faker, generated by random
seeded RNG, or pulled from a fixed pool of fictional clients. The only inputs
are public reference data: NDCs are picked from a small fixed list of
publicly-known drug NDCs, and NPIs are synthesized as Luhn-valid 10-digit
identifiers.

Why a generator rather than a "scramble real data" approach: the architecture
rule "Real PHI never leaves the production database" requires that mock data
have NO upstream dependency on real claim files. A generator removes the rule
violation entirely — there is no real-data input path to leak through.

Outputs (idempotent — running again regenerates):
  data/mock/demo_claims.txt                          — pipe-delimited, 63 cols
  data/mock/client_to_groupid_mappings_demo.csv      — fake client → group ID

Usage:
  python infrastructure/scripts/scramble_claims.py --count 100000 --seed 20260415
"""

from __future__ import annotations

import argparse
import csv
import random
import sys
from datetime import datetime, timedelta
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

from faker import Faker

# ── Canonical 63-column claims schema ──────────────────────────────────────
COLUMNS = [
    "Client Provided Unique ID", "Paid / Reversal Status Code", "BIN", "PCN",
    "Date of Service", "Date Written", "Group Number", "Cardholder ID",
    "LastName", "FirstName", "DOB", "Person Code", "Service Provider ID",
    "NDC", "Rx Number", "Quantity", "Days Supply", "Compound Code", "DAW",
    "Submitted Ingredient Cost", "Submitted Dispensing Fee",
    "Usual and Customary", "Submitted Gross Amount Due", "Submitted Tax",
    "Prescriber NPI", "Copay", "Patient Pay Amount",
    "Amount Applied to Deductible", "Amount Applied to Out of Pocket",
    "Pharmacy Total Paid", "Pharmacy Ingredient Cost Paid",
    "Pharmacy Dispensing Fee Paid", "Pharmacy Tax Paid",
    "Sell Ingredient Cost", "Sell Dispensing Fee", "Sell Tax",
    "Total Client Billed", "Other Coverage Code", "Process Date / Time",
    "Price Source", "Keyed Claim Indicator", "Selfpay Indicator",
    "Is Billable", "Historical", "Test Claim", "Location Code", "ScriptTag",
    "DrugTier", "BrandGeneric", "IsPreferred", "SenderID",
    "Network Reimbursement ID", "Amount Applied to Benefit Cap",
    "Claim Processing Fee", "Transaction Fees", "Reversal Auth Reference",
    "Statement Flag", "Bank Routing Number", "Bank Account Number",
    "Bank Account Type", "Primary Chain Code", "Debit Card Amount",
    "POS Adjustment",
]
NUM_COLUMNS = len(COLUMNS)
assert NUM_COLUMNS == 63, f"expected 63 columns, got {NUM_COLUMNS}"

# ── Fictional client pool — every claim is assigned to one of these ───────
FAKE_CLIENTS: list[tuple[str, str]] = [
    ("ACME01", "Acme Pharmaceuticals"),
    ("ACME02", "Acme Pharmaceuticals"),
    ("ACME03", "Acme Pharmaceuticals"),
    ("GLOBX01", "Globex Life Sciences"),
    ("GLOBX02", "Globex Life Sciences"),
    ("GLOBX03", "Globex Life Sciences"),
    ("GLOBX04", "Globex Life Sciences"),
    ("STARK01", "Stark Health"),
    ("STARK02", "Stark Health"),
    ("STARK03", "Stark Health"),
    ("INITC01", "Initech Therapeutics"),
    ("WAYN01", "Wayne Biotech"),
    ("OSCRP01", "Oscorp Sciences"),
    ("UMBRL01", "Umbrella Pharma"),
    ("CYBRD01", "Cyberdyne Medical"),
    ("TYREL01", "Tyrell Pharma"),
    ("CHOIC01", "Choice Therapeutics"),
    ("WELLX01", "WellnessX"),
    ("NOVAT01", "Novaterra Bio"),
    ("PINNC01", "Pinnacle Sciences"),
    ("NEXUS01", "Nexus Health"),
    ("APEX01", "Apex Generics"),
    ("ZENON01", "Zenon Therapeutics"),
    ("DEMO01", "Demo Card Program"),
    ("DEMO02", "Demo Card Program"),
]

# ── Reference-shim pools ──────────────────────────────────────────────────
# NDCs, NCPDP pharmacy IDs, and prescriber NPIs all come from the
# data/mock/_reference_shim.py file written by seed_reference_shim.py.
# Importing the frozen file ensures the generator and the seeded reference
# tables stay in lockstep — every claim joins to a real shim row.
#
# Falls back to a tiny public-NDC list if the shim file does not exist yet
# (so the script is still runnable before the seed has been loaded once).
try:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from data.mock._reference_shim import (  # type: ignore
        DRUG_NDCS as _SHIM_DRUG_NDCS,
        PHARMACY_NPIS as _SHIM_PHARMACY_NPIS,
        PRESCRIBER_NPIS as _SHIM_PRESCRIBER_NPIS,
    )
    PUBLIC_NDCS = [ndc for ndc, _name in _SHIM_DRUG_NDCS]
    SHIM_PHARMACY_NPIS = list(_SHIM_PHARMACY_NPIS)
    SHIM_PRESCRIBER_NPIS = list(_SHIM_PRESCRIBER_NPIS)
    SHIM_LOADED = True
except ImportError:
    PUBLIC_NDCS = ["00071015523", "00310075190", "00006027761", "50580046601"]
    SHIM_PHARMACY_NPIS = []
    SHIM_PRESCRIBER_NPIS = []
    SHIM_LOADED = False

# ── BIN / PCN / SenderID pools (all fictional) ────────────────────────────
DEMO_BINS = ["888001", "888002", "888003", "888004", "999001", "999002"]
DEMO_PCNS = ["DEMO", "MOCK", "TEST", "DEMORX"]
DEMO_SENDERS = ["DEMOPBM", "MOCKPBM", "DEMOSWITCH"]
DEMO_NRIDS = ["NRID-DEMO-001", "NRID-DEMO-002", "NRID-DEMO-003", "NRID-DEMO-004"]
DEMO_LOCATION_CODES = ["01", "03", "04", "05", "08"]
DEMO_DRUG_TIERS = ["1", "2", "3", "4", "SP"]
DEMO_BRAND_GENERIC = ["B", "G"]


# ── Helpers ───────────────────────────────────────────────────────────────
def luhn_check(digits: str) -> int:
    total = 0
    for i, ch in enumerate(reversed(digits)):
        n = int(ch)
        if i % 2 == 0:
            n *= 2
            if n > 9:
                n -= 9
        total += n
    return (10 - (total % 10)) % 10


def synthetic_npi(rng: random.Random) -> str:
    body = "".join(str(rng.randint(0, 9)) for _ in range(8))
    check = luhn_check("80840" + body)
    return body + str(check)


def fake_routing(rng: random.Random) -> str:
    # Leading 9 → ABA "thrift institution" range, intentionally non-real.
    return "9" + "".join(str(rng.randint(0, 9)) for _ in range(8))


def fake_account(rng: random.Random) -> str:
    return "".join(str(rng.randint(0, 9)) for _ in range(rng.randint(8, 12)))


def fake_rx_number(rng: random.Random) -> str:
    return "".join(str(rng.randint(0, 9)) for _ in range(12))


def fake_claim_id(rng: random.Random, sequence: int) -> str:
    # 20-digit identifier mimicking the IFX timestamp + sequence layout.
    prefix = datetime.now().strftime("%Y%m%d")
    seq = str(sequence).zfill(12)
    return prefix + seq


def fake_cardholder(rng: random.Random) -> str:
    return "DEMO" + "".join(str(rng.randint(0, 9)) for _ in range(9))


def random_amount(rng: random.Random, low: float, high: float) -> Decimal:
    return Decimal(str(rng.uniform(low, high))).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )


# ── One-row generator ─────────────────────────────────────────────────────
def generate_row(
    sequence: int,
    rng: random.Random,
    faker: Faker,
    cardholder_pool: list[str],
    npi_pool: list[str],
    pharmacy_pool: list[str],
    routing_pool: list[str],
    account_pool: list[str],
) -> list[str]:
    group_id, _company = rng.choice(FAKE_CLIENTS)
    cardholder = rng.choice(cardholder_pool)

    # Member identity — FULLY fake names from Faker, deterministic-per-cardholder.
    # Seeding Faker per cardholder means repeated cardholders get the same name.
    sub_faker = Faker()
    sub_faker.seed_instance(int(cardholder.replace("DEMO", "") or "0"))
    last_name = sub_faker.last_name().upper()
    first_name = sub_faker.first_name().upper()
    dob_dt = sub_faker.date_of_birth(minimum_age=18, maximum_age=89)
    dob = dob_dt.strftime("%m/%d/%Y")

    # Service & write dates within the past 90 days (mock data is "recent").
    days_back = rng.randint(0, 90)
    service_dt = datetime.now() - timedelta(days=days_back)
    written_dt = service_dt - timedelta(days=rng.randint(0, 3))
    process_dt = service_dt + timedelta(hours=rng.randint(1, 23))

    # Money — realistic distributions, all derived from Decimal.
    quantity = rng.choice([30, 60, 90, 14, 7, 100, 180])
    days_supply = rng.choice([30, 60, 90, 14, 7])
    sub_ing = random_amount(rng, 5, 4500)
    sub_disp = random_amount(rng, 0.5, 60)
    sub_tax = Decimal("0.00")
    sub_gross = (sub_ing + sub_disp + sub_tax).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )
    usual_customary = (sub_gross * Decimal(str(rng.uniform(1.0, 1.10)))).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )

    copay = random_amount(rng, 0, min(150, float(sub_gross) * 0.25))
    patient_pay = copay
    deductible_applied = random_amount(rng, 0, 50) if rng.random() < 0.2 else Decimal("0.00")
    oop_applied = (copay + deductible_applied).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )

    ph_ing = (sub_ing * Decimal("0.85")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    ph_disp = sub_disp
    ph_tax = sub_tax
    ph_total = (ph_ing + ph_disp + ph_tax).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )

    sell_ing = (sub_ing * Decimal("0.92")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    sell_disp = sub_disp
    sell_tax = sub_tax
    total_billed = (sell_ing + sell_disp + sell_tax).quantize(
        Decimal("0.01"), rounding=ROUND_HALF_UP
    )

    fee_processing = random_amount(rng, 1.5, 3.5)
    fee_transaction = random_amount(rng, 0.25, 1.0)

    row = [""] * NUM_COLUMNS

    def put(name: str, value):
        row[COLUMNS.index(name)] = str(value)

    put("Client Provided Unique ID", fake_claim_id(rng, sequence))
    put("Paid / Reversal Status Code", "P" if rng.random() > 0.05 else "R")
    put("BIN", rng.choice(DEMO_BINS))
    put("PCN", rng.choice(DEMO_PCNS))
    put("Date of Service", service_dt.strftime("%m/%d/%Y"))
    put("Date Written", written_dt.strftime("%m/%d/%Y"))
    put("Group Number", group_id)
    put("Cardholder ID", cardholder)
    put("LastName", last_name)
    put("FirstName", first_name)
    put("DOB", dob)
    put("Person Code", rng.choice(["01", "02", "03"]))
    put("Service Provider ID", rng.choice(pharmacy_pool))
    put("NDC", rng.choice(PUBLIC_NDCS))
    put("Rx Number", fake_rx_number(rng))
    put("Quantity", f"{quantity}.00")
    put("Days Supply", days_supply)
    put("Compound Code", "1")
    put("DAW", "0")
    put("Submitted Ingredient Cost", sub_ing)
    put("Submitted Dispensing Fee", sub_disp)
    put("Usual and Customary", usual_customary)
    put("Submitted Gross Amount Due", sub_gross)
    put("Submitted Tax", sub_tax)
    put("Prescriber NPI", rng.choice(npi_pool))
    put("Copay", copay)
    put("Patient Pay Amount", patient_pay)
    put("Amount Applied to Deductible", deductible_applied)
    put("Amount Applied to Out of Pocket", oop_applied)
    put("Pharmacy Total Paid", ph_total)
    put("Pharmacy Ingredient Cost Paid", ph_ing)
    put("Pharmacy Dispensing Fee Paid", ph_disp)
    put("Pharmacy Tax Paid", ph_tax)
    put("Sell Ingredient Cost", sell_ing)
    put("Sell Dispensing Fee", sell_disp)
    put("Sell Tax", sell_tax)
    put("Total Client Billed", total_billed)
    put("Other Coverage Code", "08")
    put("Process Date / Time", process_dt.strftime("%m/%d/%Y %H:%M:%S"))
    put("Price Source", "14")
    put("Keyed Claim Indicator", "")
    put("Selfpay Indicator", "")
    put("Is Billable", "")
    put("Historical", "0")
    put("Test Claim", "")
    put("Location Code", rng.choice(DEMO_LOCATION_CODES))
    put("ScriptTag", "")
    put("DrugTier", rng.choice(DEMO_DRUG_TIERS))
    put("BrandGeneric", rng.choice(DEMO_BRAND_GENERIC))
    put("IsPreferred", rng.choice(["Y", "N"]))
    put("SenderID", rng.choice(DEMO_SENDERS))
    put("Network Reimbursement ID", rng.choice(DEMO_NRIDS))
    put("Amount Applied to Benefit Cap", "0.00")
    put("Claim Processing Fee", fee_processing)
    put("Transaction Fees", fee_transaction)
    put("Reversal Auth Reference", "")
    put("Statement Flag", "0")
    put("Bank Routing Number", rng.choice(routing_pool))
    put("Bank Account Number", rng.choice(account_pool))
    put("Bank Account Type", rng.choice(["Checking", "Savings"]))
    put("Primary Chain Code", str(rng.randint(100, 999)))
    put("Debit Card Amount", "0.00")
    put("POS Adjustment", "0.00")

    return row


# ── Pool builders (run once before generation) ────────────────────────────
def build_pools(rng: random.Random) -> dict:
    """Pre-generate fixed pools.

    NPI and pharmacy pools come from the reference shim if it has been
    loaded — that's how the generated claims join cleanly to the seeded
    drug_database.drugs / pharmacy_dir.ncpdp_pharmacies / prescriber_dir
    .prescribers tables. Falls back to Luhn-valid synthetic identifiers
    when the shim isn't available (e.g. first-time scaffold).
    """
    npis = SHIM_PRESCRIBER_NPIS if SHIM_PRESCRIBER_NPIS else [synthetic_npi(rng) for _ in range(5_000)]
    pharmacies = SHIM_PHARMACY_NPIS if SHIM_PHARMACY_NPIS else [synthetic_npi(rng) for _ in range(800)]
    return {
        "cardholders": [fake_cardholder(rng) for _ in range(2_000)],
        "npis": npis,
        "pharmacies": pharmacies,
        "routings": [fake_routing(rng) for _ in range(40)],
        "accounts": [fake_account(rng) for _ in range(40)],
    }


# ── Driver ────────────────────────────────────────────────────────────────
def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--count", type=int, default=100_000,
                   help="number of claim rows to generate")
    p.add_argument("--seed", type=int, default=20260415)
    p.add_argument("--output", type=Path,
                   default=Path("data/mock/demo_claims.txt"))
    p.add_argument("--mapping-output", type=Path,
                   default=Path("data/mock/client_to_groupid_mappings_demo.csv"))
    args = p.parse_args()

    rng = random.Random(args.seed)
    faker = Faker()
    Faker.seed(args.seed)

    pools = build_pools(rng)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.mapping_output.parent.mkdir(parents=True, exist_ok=True)

    print(f"[generate] seed={args.seed} count={args.count:,}")
    print(f"[generate] cardholders={len(pools['cardholders']):,} "
          f"npis={len(pools['npis']):,} pharmacies={len(pools['pharmacies']):,}")

    with args.output.open("w", encoding="utf-8", newline="") as out:
        out.write("|".join(COLUMNS) + "\n")
        for i in range(args.count):
            row = generate_row(
                sequence=i,
                rng=rng,
                faker=faker,
                cardholder_pool=pools["cardholders"],
                npi_pool=pools["npis"],
                pharmacy_pool=pools["pharmacies"],
                routing_pool=pools["routings"],
                account_pool=pools["accounts"],
            )
            out.write("|".join(row) + "\n")
            if (i + 1) % 10_000 == 0:
                print(f"  ... {i + 1:,} rows")

    # Mapping CSV — every fake client → fake group ID.
    seen = set()
    mapping_rows: list[tuple[str, str]] = []
    for group_id, company in FAKE_CLIENTS:
        if group_id in seen:
            continue
        seen.add(group_id)
        mapping_rows.append((company, group_id))
    mapping_rows.sort()

    with args.mapping_output.open("w", encoding="utf-8", newline="") as csvf:
        writer = csv.writer(csvf)
        writer.writerow(["Company", "Group ID"])
        writer.writerows(mapping_rows)

    print(f"[generate] wrote {args.count:,} rows → {args.output}")
    print(f"[generate] wrote {len(mapping_rows)} client mappings → {args.mapping_output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
