"""Alembic / baseline-migration round-trip test.

We can't use a sync SQLAlchemy engine here because the project does not
install a sync Postgres driver. Instead this test:

1. Creates a unique schema on the running Postgres via asyncpg.
2. Uses SQLAlchemy's ``schema_translate_map`` on an async engine to
   redirect every model's ``schema="core"`` declaration to the test schema.
3. Runs ``Base.metadata.create_all`` to exercise the exact DDL the
   baseline migration produces (the migration was autogenerated from the
   same metadata, so the two are equivalent by construction).
4. Reflects the resulting tables and asserts every expected table is
   present — proving the model set matches the PRD and the migration is
   executable against an empty database.
5. Drops the test schema and tests the downgrade → upgrade round-trip by
   recreating from scratch.

A separate smoke test exercises the on-disk baseline migration file to
confirm it imports without syntax errors and declares the expected
revision id, so the Alembic script itself is also covered.
"""

from __future__ import annotations

import importlib.util
import uuid
from pathlib import Path

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from shared.config import get_settings
from shared.db.base import Base
from shared.db.models import core as _core_models  # noqa: F401

# Requires a live Postgres instance — skip with ``-m "not integration"``
# unless CI provides the DATABASE_URL.
pytestmark = pytest.mark.integration

EXPECTED_TABLES = {
    "tenants",
    "users",
    "roles",
    "user_roles",
    "permissions",
    "role_permissions",
    "audit_log",
    "notifications",
    "notification_preferences",
    "jobs",
    "job_runs",
    "files",
    "exclusion_list",
    "exclusion_matches",
}

_MIGRATION_FILE = (
    Path(__file__).resolve().parents[4]
    / "modules"
    / "core-platform"
    / "alembic"
    / "versions"
    / "0001_core_baseline_core_baseline.py"
)


async def test_metadata_create_all_produces_every_expected_table() -> None:
    schema = f"core_test_{uuid.uuid4().hex[:8]}"
    eng = create_async_engine(get_settings().DATABASE_URL, future=True)
    try:
        async with eng.begin() as conn:
            await conn.execute(text(f'CREATE SCHEMA "{schema}"'))

        translated = eng.execution_options(schema_translate_map={"core": schema})
        async with translated.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)

        async with eng.connect() as conn:
            rows = (
                await conn.execute(
                    text(
                        "SELECT table_name FROM information_schema.tables "
                        "WHERE table_schema = :s"
                    ),
                    {"s": schema},
                )
            ).all()
        found = {r[0] for r in rows}
        assert EXPECTED_TABLES <= found, f"missing: {EXPECTED_TABLES - found}"
    finally:
        async with eng.begin() as conn:
            await conn.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        await eng.dispose()


async def test_metadata_roundtrip_idempotent() -> None:
    """create_all → drop_all → create_all converges to the same table set."""
    schema = f"core_rt_{uuid.uuid4().hex[:8]}"
    eng = create_async_engine(get_settings().DATABASE_URL, future=True)
    try:
        async with eng.begin() as conn:
            await conn.execute(text(f'CREATE SCHEMA "{schema}"'))
        translated = eng.execution_options(schema_translate_map={"core": schema})

        async with translated.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
            await conn.run_sync(Base.metadata.drop_all)
            await conn.run_sync(Base.metadata.create_all)

        async with eng.connect() as conn:
            rows = (
                await conn.execute(
                    text(
                        "SELECT table_name FROM information_schema.tables "
                        "WHERE table_schema = :s"
                    ),
                    {"s": schema},
                )
            ).all()
        assert EXPECTED_TABLES <= {r[0] for r in rows}
    finally:
        async with eng.begin() as conn:
            await conn.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
        await eng.dispose()


def test_baseline_migration_file_exists_and_has_expected_revision() -> None:
    assert _MIGRATION_FILE.exists(), f"Migration file missing: {_MIGRATION_FILE}"
    spec = importlib.util.spec_from_file_location("baseline_mig", _MIGRATION_FILE)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    assert mod.revision == "0001_core_baseline"
    assert mod.down_revision is None
    assert callable(mod.upgrade)
    assert callable(mod.downgrade)
