"""B9.C Tier B batch 04 (9 NDC/GCN-keyed join tables).

Tables: RMEDIN0, RMEDIS0, RMEDNGH0, RMEDNGM0, RMEDNGR0, RMEDNIN0, RMEDNIS0, RMEDNMH0, RMEDNMR0.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_04.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='RMEDIN0_MEDID_INACTV_LINK',
        columns=('MEDID', 'HIC_SEQN', 'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'),
        coercers={'MEDID': str, 'HIC_SEQN': str, 'INACTV_NOT_PRES_CNT': str, 'INACTV_PRES_CNT': str},
        nullable=frozenset({'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDIN0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID', 'HIC_SEQN'),
    ),
    TableSpec(
        table_name='RMEDIS0_MEDID_STUDY_TABLE',
        columns=('MEDID', 'TOTAL_PRODUCTS_CNT', 'PRODUCTS_RESEARCHED_CNT'),
        coercers={'MEDID': str, 'TOTAL_PRODUCTS_CNT': str, 'PRODUCTS_RESEARCHED_CNT': str},
        nullable=frozenset({'PRODUCTS_RESEARCHED_CNT', 'TOTAL_PRODUCTS_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDIS0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID',),
    ),
    TableSpec(
        table_name='RMEDNGH0_NDC_GEN_MEDID_HIST',
        columns=('NDC', 'PRODUCTION_DATE', 'PREV_MEDID', 'PREV_MEDID_NAME_SOURCE_CD', 'PREV_MEDID_OLD_STATUS_CD', 'PREV_MEDID_NEW_STATUS_CD', 'PREV_MEDID_DESC', 'CURR_MEDID', 'CURR_MEDID_NAME_SOURCE_CD', 'CURR_MEDID_OLD_STATUS_CD', 'CURR_MEDID_NEW_STATUS_CD', 'CURR_MEDID_DESC'),
        coercers={'NDC': str, 'PRODUCTION_DATE': str, 'PREV_MEDID': str, 'PREV_MEDID_NAME_SOURCE_CD': str, 'PREV_MEDID_OLD_STATUS_CD': str, 'PREV_MEDID_NEW_STATUS_CD': str, 'PREV_MEDID_DESC': str, 'CURR_MEDID': str, 'CURR_MEDID_NAME_SOURCE_CD': str, 'CURR_MEDID_OLD_STATUS_CD': str, 'CURR_MEDID_NEW_STATUS_CD': str, 'CURR_MEDID_DESC': str},
        nullable=frozenset({'CURR_MEDID_OLD_STATUS_CD'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDNGH0',
        delta_semantics=DeltaSemantics.APPEND_ONLY,
        natural_key=('NDC', 'PRODUCTION_DATE', 'PREV_MEDID'),
    ),
    TableSpec(
        table_name='RMEDNGM0_NDC_GEN_MEDID',
        columns=('NDC', 'MEDID'),
        coercers={'NDC': str, 'MEDID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDNGM0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'MEDID'),
    ),
    TableSpec(
        table_name='RMEDNGR0_NDC_GEN_MEDID_REASON',
        columns=('NDC', 'PRODUCTION_DATE', 'MOVE_REASON_CD'),
        coercers={'NDC': str, 'PRODUCTION_DATE': str, 'MOVE_REASON_CD': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDNGR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC',),
    ),
    TableSpec(
        table_name='RMEDNIN0_MNID_INACTV_LINK',
        columns=('MED_NAME_ID', 'HIC_SEQN', 'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'),
        coercers={'MED_NAME_ID': str, 'HIC_SEQN': str, 'INACTV_NOT_PRES_CNT': str, 'INACTV_PRES_CNT': str},
        nullable=frozenset({'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDNIN0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MED_NAME_ID', 'HIC_SEQN'),
    ),
    TableSpec(
        table_name='RMEDNIS0_MED_NAME_STUDY_TABLE',
        columns=('MED_NAME_ID', 'TOTAL_PRODUCTS_CNT', 'PRODUCTS_RESEARCHED_CNT'),
        coercers={'MED_NAME_ID': str, 'TOTAL_PRODUCTS_CNT': str, 'PRODUCTS_RESEARCHED_CNT': str},
        nullable=frozenset({'PRODUCTS_RESEARCHED_CNT', 'TOTAL_PRODUCTS_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDNIS0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MED_NAME_ID',),
    ),
    TableSpec(
        table_name='RMEDNMH0_NDC_MEDID_HIST',
        columns=('NDC', 'PRODUCTION_DATE', 'PREV_MEDID', 'PREV_MEDID_NAME_SOURCE_CD', 'PREV_MEDID_OLD_STATUS_CD', 'PREV_MEDID_NEW_STATUS_CD', 'PREV_MEDID_DESC', 'CURR_MEDID', 'CURR_MEDID_NAME_SOURCE_CD', 'CURR_MEDID_OLD_STATUS_CD', 'CURR_MEDID_NEW_STATUS_CD', 'CURR_MEDID_DESC'),
        coercers={'NDC': str, 'PRODUCTION_DATE': str, 'PREV_MEDID': str, 'PREV_MEDID_NAME_SOURCE_CD': str, 'PREV_MEDID_OLD_STATUS_CD': str, 'PREV_MEDID_NEW_STATUS_CD': str, 'PREV_MEDID_DESC': str, 'CURR_MEDID': str, 'CURR_MEDID_NAME_SOURCE_CD': str, 'CURR_MEDID_OLD_STATUS_CD': str, 'CURR_MEDID_NEW_STATUS_CD': str, 'CURR_MEDID_DESC': str},
        nullable=frozenset({'CURR_MEDID_OLD_STATUS_CD'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDNMH0',
        delta_semantics=DeltaSemantics.APPEND_ONLY,
        natural_key=('NDC', 'PRODUCTION_DATE', 'PREV_MEDID'),
    ),
    TableSpec(
        table_name='RMEDNMR0_NDC_MEDID_REASON',
        columns=('NDC', 'PRODUCTION_DATE', 'MOVE_REASON_CD'),
        coercers={'NDC': str, 'PRODUCTION_DATE': str, 'MOVE_REASON_CD': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDNMR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC',),
    ),
]
