"""B9.C Tier B batch 05 (9 NDC/GCN-keyed join tables).

Tables: RMEDRIN0, RMEDRIS0, RMEDSPC0, RMIGC1, RMINDC1, RMINMID1, RNDCAT0, RNDCINH0, RNDCINR0.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_05.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='RMEDRIN0_RMID_INACTV_LINK',
        columns=('ROUTED_MED_ID', 'HIC_SEQN', 'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'),
        coercers={'ROUTED_MED_ID': str, 'HIC_SEQN': str, 'INACTV_NOT_PRES_CNT': str, 'INACTV_PRES_CNT': str},
        nullable=frozenset({'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDRIN0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_MED_ID', 'HIC_SEQN'),
    ),
    TableSpec(
        table_name='RMEDRIS0_ROUTED_MED_STDY_TBL',
        columns=('ROUTED_MED_ID', 'TOTAL_PRODUCTS_CNT', 'PRODUCTS_RESEARCHED_CNT'),
        coercers={'ROUTED_MED_ID': str, 'TOTAL_PRODUCTS_CNT': str, 'PRODUCTS_RESEARCHED_CNT': str},
        nullable=frozenset({'PRODUCTS_RESEARCHED_CNT', 'TOTAL_PRODUCTS_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDRIS0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_MED_ID',),
    ),
    TableSpec(
        table_name='RMEDSPC0_SPECIFICATION',
        columns=('MEDID', 'MEDID_SPECIFICATION_CODE'),
        coercers={'MEDID': str, 'MEDID_SPECIFICATION_CODE': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDSPC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID', 'MEDID_SPECIFICATION_CODE'),
    ),
    TableSpec(
        table_name='RMIGC1_MEDID_GCNSEQNO_LINK',
        columns=('GCN_SEQNO', 'MEDID'),
        coercers={'GCN_SEQNO': str, 'MEDID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMIGC1',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'MEDID'),
    ),
    TableSpec(
        table_name='RMINDC1_NDC_MEDID',
        columns=('NDC', 'MEDID'),
        coercers={'NDC': str, 'MEDID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMINDC1',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'MEDID'),
    ),
    TableSpec(
        table_name='RMINMID1_MED_NAME',
        columns=('MED_NAME_ID', 'MED_NAME', 'MED_NAME_TYPE_CD', 'MED_STATUS_CD'),
        coercers={'MED_NAME_ID': str, 'MED_NAME': str, 'MED_NAME_TYPE_CD': str, 'MED_STATUS_CD': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMINMID1',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MED_NAME_ID', 'MED_NAME'),
    ),
    TableSpec(
        table_name='RNDCAT0_NDC_ATTRIBUTE',
        columns=('NDC', 'NDC_ATTRIBUTE_TYPE_CD', 'NDC_ATTRIBUTE_SN', 'NDC_ATTRIBUTE_VALUE'),
        coercers={'NDC': str, 'NDC_ATTRIBUTE_TYPE_CD': str, 'NDC_ATTRIBUTE_SN': str, 'NDC_ATTRIBUTE_VALUE': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RNDCAT0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'NDC_ATTRIBUTE_TYPE_CD'),
    ),
    TableSpec(
        table_name='RNDCINH0_NDC_INACTV_LINK',
        columns=('NDC', 'HIC_SEQN'),
        coercers={'NDC': str, 'HIC_SEQN': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RNDCINH0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'HIC_SEQN'),
    ),
    TableSpec(
        table_name='RNDCINR0_INACTV_REVIEWED',
        columns=('NDC',),
        coercers={'NDC': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RNDCINR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC',),
    ),
]
