"""B9.C Tier B batch 08 (9 NDC/GCN-keyed join tables).

Tables: RPEIRR0, RRTGNGC0, RRTGNND0, RTMDFCG0, RTMMICG0, RTMNCG0, RTMNID0, RTMNMCG0, RTMRMCG0.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_08.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='RPEIRR0_RTD_DF_MED_RT_RELATION',
        columns=('ROUTED_DOSAGE_FORM_MED_ID', 'PARENT_RT_ID', 'CLINICAL_RT_ID', 'RELATION_INACTIVE_DATE'),
        coercers={'ROUTED_DOSAGE_FORM_MED_ID': str, 'PARENT_RT_ID': str, 'CLINICAL_RT_ID': str, 'RELATION_INACTIVE_DATE': str},
        nullable=frozenset({'RELATION_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIRR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_DOSAGE_FORM_MED_ID', 'PARENT_RT_ID'),
    ),
    TableSpec(
        table_name='RRTGNGC0_RTD_GEN_GCNSEQNO_LNK',
        columns=('GCN_SEQNO', 'ROUTED_GEN_ID'),
        coercers={'GCN_SEQNO': str, 'ROUTED_GEN_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RRTGNGC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'ROUTED_GEN_ID'),
    ),
    TableSpec(
        table_name='RRTGNND0_ROUTED_GEN_NDC_LINK',
        columns=('NDC', 'ROUTED_GEN_ID'),
        coercers={'NDC': str, 'ROUTED_GEN_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RRTGNND0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'ROUTED_GEN_ID'),
    ),
    TableSpec(
        table_name='RTMDFCG0_TM_RTD_DF_CNFSN_GRP',
        columns=('ROUTED_DOSAGE_FORM_MED_ID', 'TM_GROUP_ID'),
        coercers={'ROUTED_DOSAGE_FORM_MED_ID': str, 'TM_GROUP_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RTMDFCG0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_DOSAGE_FORM_MED_ID', 'TM_GROUP_ID'),
    ),
    TableSpec(
        table_name='RTMMICG0_TM_MED_CNFSN_GRP',
        columns=('MEDID', 'TM_GROUP_ID'),
        coercers={'MEDID': str, 'TM_GROUP_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RTMMICG0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID', 'TM_GROUP_ID'),
    ),
    TableSpec(
        table_name='RTMNCG0_TM_NDC_CNFSN_GRP',
        columns=('NDC', 'TM_GROUP_ID'),
        coercers={'NDC': str, 'TM_GROUP_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RTMNCG0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'TM_GROUP_ID'),
    ),
    TableSpec(
        table_name='RTMNID0_TM_NDC',
        columns=('NDC', 'TM_NAME_TYPE_ID', 'TM_SOURCE_ID', 'TM_IND', 'TM_ALT_NDC_DESC'),
        coercers={'NDC': str, 'TM_NAME_TYPE_ID': str, 'TM_SOURCE_ID': str, 'TM_IND': str, 'TM_ALT_NDC_DESC': str},
        nullable=frozenset({'TM_SOURCE_ID'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RTMNID0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'TM_NAME_TYPE_ID'),
    ),
    TableSpec(
        table_name='RTMNMCG0_TM_MED_NAME_CNFSN_GRP',
        columns=('MED_NAME_ID', 'TM_GROUP_ID'),
        coercers={'MED_NAME_ID': str, 'TM_GROUP_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RTMNMCG0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MED_NAME_ID', 'TM_GROUP_ID'),
    ),
    TableSpec(
        table_name='RTMRMCG0_TM_RTD_MED_CNFSN_GRP',
        columns=('ROUTED_MED_ID', 'TM_GROUP_ID'),
        coercers={'ROUTED_MED_ID': str, 'TM_GROUP_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RTMRMCG0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_MED_ID', 'TM_GROUP_ID'),
    ),
]
