"""B9.C Tier B batch 02 (9 NDC/GCN-keyed join tables).

Tables: RETCMDH0, RETCMED0, RETCMNM0, RETCNDC0, RETCNDH0, RGCN0, RGCNINH0, RGCNINS0, RHIC3L2.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_02.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='RETCMDH0_ETC_MEDID_HIST',
        columns=('MEDID', 'ETC_ID', 'ETC_REVISION_SEQNO', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND', 'ETC_CHANGE_TYPE_CODE', 'ETC_EFFECTIVE_DATE'),
        coercers={'MEDID': str, 'ETC_ID': str, 'ETC_REVISION_SEQNO': str, 'ETC_COMMON_USE_IND': str, 'ETC_DEFAULT_USE_IND': str, 'ETC_CHANGE_TYPE_CODE': str, 'ETC_EFFECTIVE_DATE': str},
        nullable=frozenset({'ETC_CHANGE_TYPE_CODE', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND', 'ETC_EFFECTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCMDH0',
        delta_semantics=DeltaSemantics.APPEND_ONLY,
        natural_key=('MEDID', 'ETC_ID', 'ETC_REVISION_SEQNO'),
    ),
    TableSpec(
        table_name='RETCMED0_ETC_MEDID',
        columns=('MEDID', 'ETC_ID', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND'),
        coercers={'MEDID': str, 'ETC_ID': str, 'ETC_COMMON_USE_IND': str, 'ETC_DEFAULT_USE_IND': str},
        nullable=frozenset({'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCMED0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID', 'ETC_ID'),
    ),
    TableSpec(
        table_name='RETCMNM0_ETC_MED_NAME_ID',
        columns=('MED_NAME_ID', 'ETC_ID'),
        coercers={'MED_NAME_ID': str, 'ETC_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCMNM0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MED_NAME_ID', 'ETC_ID'),
    ),
    TableSpec(
        table_name='RETCNDC0_ETC_NDC',
        columns=('NDC', 'ETC_ID', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND'),
        coercers={'NDC': str, 'ETC_ID': str, 'ETC_COMMON_USE_IND': str, 'ETC_DEFAULT_USE_IND': str},
        nullable=frozenset({'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCNDC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'ETC_ID'),
    ),
    TableSpec(
        table_name='RETCNDH0_ETC_NDC_HIST',
        columns=('NDC', 'ETC_ID', 'ETC_REVISION_SEQNO', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND', 'ETC_CHANGE_TYPE_CODE', 'ETC_EFFECTIVE_DATE'),
        coercers={'NDC': str, 'ETC_ID': str, 'ETC_REVISION_SEQNO': str, 'ETC_COMMON_USE_IND': str, 'ETC_DEFAULT_USE_IND': str, 'ETC_CHANGE_TYPE_CODE': str, 'ETC_EFFECTIVE_DATE': str},
        nullable=frozenset({'ETC_CHANGE_TYPE_CODE', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND', 'ETC_EFFECTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCNDH0',
        delta_semantics=DeltaSemantics.APPEND_ONLY,
        natural_key=('NDC', 'ETC_ID', 'ETC_REVISION_SEQNO'),
    ),
    TableSpec(
        table_name='RGCN0_GCN_GCNSEQNO_LINK',
        columns=('GCN_SEQNO', 'GCN'),
        coercers={'GCN_SEQNO': str, 'GCN': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RGCN0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'GCN'),
    ),
    TableSpec(
        table_name='RGCNINH0_GCNSEQNO_INACTV_LINK',
        columns=('GCN_SEQNO', 'HIC_SEQN', 'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'),
        coercers={'GCN_SEQNO': str, 'HIC_SEQN': str, 'INACTV_NOT_PRES_CNT': str, 'INACTV_PRES_CNT': str},
        nullable=frozenset({'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RGCNINH0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'HIC_SEQN'),
    ),
    TableSpec(
        table_name='RGCNINS0_STUDY_TABLE',
        columns=('GCN_SEQNO', 'TOTAL_PRODUCTS_CNT', 'PRODUCTS_RESEARCHED_CNT'),
        coercers={'GCN_SEQNO': str, 'TOTAL_PRODUCTS_CNT': str, 'PRODUCTS_RESEARCHED_CNT': str},
        nullable=frozenset({'PRODUCTS_RESEARCHED_CNT', 'TOTAL_PRODUCTS_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RGCNINS0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO',),
    ),
    TableSpec(
        table_name='RHIC3L2_HIC3_HICLSEQNO_LINK',
        columns=('HICL_SEQNO', 'HIC3_SEQN', 'HIC3', 'HIC3_RELNO'),
        coercers={'HICL_SEQNO': str, 'HIC3_SEQN': str, 'HIC3': str, 'HIC3_RELNO': str},
        nullable=frozenset({'HIC3', 'HIC3_RELNO'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHIC3L2',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HICL_SEQNO', 'HIC3_SEQN'),
    ),
]
