"""B9.C Tier B batch 07 (9 NDC/GCN-keyed join tables).

Tables: RPEIMRR0, RPEINA0, RPEIND0, RPEINR0, RPEIRA0, RPEIRD0, RPEIRMA0, RPEIRMD0, RPEIRMR0.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_07.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='RPEIMRR0_MED_RT_RELATION',
        columns=('MEDID', 'PARENT_RT_ID', 'CLINICAL_RT_ID', 'RELATION_INACTIVE_DATE'),
        coercers={'MEDID': str, 'PARENT_RT_ID': str, 'CLINICAL_RT_ID': str, 'RELATION_INACTIVE_DATE': str},
        nullable=frozenset({'RELATION_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIMRR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID', 'PARENT_RT_ID'),
    ),
    TableSpec(
        table_name='RPEINA0_MED_NAME_ATTRIBUTE',
        columns=('MED_NAME_ID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN', 'ATTRIBUTE_VALUE', 'LINK_INACTIVE_DATE'),
        coercers={'MED_NAME_ID': str, 'ATTRIBUTE_CODE': str, 'ATTRIBUTE_SN': str, 'ATTRIBUTE_VALUE': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEINA0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MED_NAME_ID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN'),
    ),
    TableSpec(
        table_name='RPEIND0_NDC_DF_LINK',
        columns=('NDC', 'DOSAGE_FORM_ID', 'DOSAGE_FORM_TYPE_ID'),
        coercers={'NDC': str, 'DOSAGE_FORM_ID': str, 'DOSAGE_FORM_TYPE_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIND0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'DOSAGE_FORM_ID'),
    ),
    TableSpec(
        table_name='RPEINR0_NDC_RT_RELATION',
        columns=('NDC', 'PARENT_RT_ID', 'CLINICAL_RT_ID', 'RT_LABELED_ID'),
        coercers={'NDC': str, 'PARENT_RT_ID': str, 'CLINICAL_RT_ID': str, 'RT_LABELED_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEINR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'PARENT_RT_ID'),
    ),
    TableSpec(
        table_name='RPEIRA0_RT_DF_MED_ATTRIBUTE',
        columns=('ROUTED_DOSAGE_FORM_MED_ID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN', 'ATTRIBUTE_VALUE', 'LINK_INACTIVE_DATE'),
        coercers={'ROUTED_DOSAGE_FORM_MED_ID': str, 'ATTRIBUTE_CODE': str, 'ATTRIBUTE_SN': str, 'ATTRIBUTE_VALUE': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIRA0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_DOSAGE_FORM_MED_ID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN'),
    ),
    TableSpec(
        table_name='RPEIRD0_RTD_DF_MED_DF_LINK',
        columns=('ROUTED_DOSAGE_FORM_MED_ID', 'DOSAGE_FORM_ID', 'DOSAGE_FORM_TYPE_ID', 'LINK_INACTIVE_DATE'),
        coercers={'ROUTED_DOSAGE_FORM_MED_ID': str, 'DOSAGE_FORM_ID': str, 'DOSAGE_FORM_TYPE_ID': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIRD0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_DOSAGE_FORM_MED_ID', 'DOSAGE_FORM_ID'),
    ),
    TableSpec(
        table_name='RPEIRMA0_RTD_MED_ATTRIBUTE',
        columns=('ROUTED_MED_ID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN', 'ATTRIBUTE_VALUE', 'LINK_INACTIVE_DATE'),
        coercers={'ROUTED_MED_ID': str, 'ATTRIBUTE_CODE': str, 'ATTRIBUTE_SN': str, 'ATTRIBUTE_VALUE': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIRMA0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_MED_ID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN'),
    ),
    TableSpec(
        table_name='RPEIRMD0_RTD_MED_DF_LINK',
        columns=('ROUTED_MED_ID', 'DOSAGE_FORM_ID', 'DOSAGE_FORM_TYPE_ID', 'LINK_INACTIVE_DATE'),
        coercers={'ROUTED_MED_ID': str, 'DOSAGE_FORM_ID': str, 'DOSAGE_FORM_TYPE_ID': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIRMD0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_MED_ID', 'DOSAGE_FORM_ID'),
    ),
    TableSpec(
        table_name='RPEIRMR0_RTD_MED_RT_RELATION',
        columns=('ROUTED_MED_ID', 'PARENT_RT_ID', 'CLINICAL_RT_ID', 'RELATION_INACTIVE_DATE'),
        coercers={'ROUTED_MED_ID': str, 'PARENT_RT_ID': str, 'CLINICAL_RT_ID': str, 'RELATION_INACTIVE_DATE': str},
        nullable=frozenset({'RELATION_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIRMR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_MED_ID', 'PARENT_RT_ID'),
    ),
]
