"""B9.C Tier B batch 03 (9 NDC/GCN-keyed join tables).

Tables: RHIC4D2, RHICCAS1, RHICD5, RHICHCR0, RHICL1, RHICLSQ1, RHICLSQ2, RMEDDIN0, RMEDDIS0.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_03.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='RHIC4D2_HIC_BASE_ING_DESC',
        columns=('HIC4_SEQN', 'HIC4', 'HIC4_DESC', 'HIC4_ROOT', 'HIC4_POTENTIALLY_INACTV_IND', 'ING_STATUS_CD'),
        coercers={'HIC4_SEQN': str, 'HIC4': str, 'HIC4_DESC': str, 'HIC4_ROOT': str, 'HIC4_POTENTIALLY_INACTV_IND': str, 'ING_STATUS_CD': str},
        nullable=frozenset({'HIC4', 'HIC4_DESC', 'HIC4_POTENTIALLY_INACTV_IND', 'HIC4_ROOT', 'ING_STATUS_CD'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHIC4D2',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HIC4_SEQN', 'HIC4'),
    ),
    TableSpec(
        table_name='RHICCAS1_HIC_CAS_LINK',
        columns=('HIC_SEQN', 'CAS9_TBL', 'HIC'),
        coercers={'HIC_SEQN': str, 'CAS9_TBL': str, 'HIC': str},
        nullable=frozenset({'CAS9_TBL', 'HIC'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHICCAS1',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HIC_SEQN', 'CAS9_TBL'),
    ),
    TableSpec(
        table_name='RHICD5_HIC_DESC',
        columns=('HIC_SEQN', 'HIC', 'HIC_DESC', 'HIC_ROOT', 'HIC_POTENTIALLY_INACTV_IND', 'ING_STATUS_CD'),
        coercers={'HIC_SEQN': str, 'HIC': str, 'HIC_DESC': str, 'HIC_ROOT': str, 'HIC_POTENTIALLY_INACTV_IND': str, 'ING_STATUS_CD': str},
        nullable=frozenset({'HIC', 'HIC_DESC', 'HIC_POTENTIALLY_INACTV_IND', 'HIC_ROOT', 'ING_STATUS_CD'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHICD5',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HIC_SEQN', 'HIC'),
    ),
    TableSpec(
        table_name='RHICHCR0_HIC_HIC_LINK',
        columns=('HIC_SEQN', 'RELATED_HIC_SEQN'),
        coercers={'HIC_SEQN': str, 'RELATED_HIC_SEQN': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHICHCR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HIC_SEQN', 'RELATED_HIC_SEQN'),
    ),
    TableSpec(
        table_name='RHICL1_HIC_HICLSEQNO_LINK',
        columns=('HICL_SEQNO', 'HIC_SEQN', 'HIC_REL_NO', 'HIC'),
        coercers={'HICL_SEQNO': str, 'HIC_SEQN': str, 'HIC_REL_NO': str, 'HIC': str},
        nullable=frozenset({'HIC', 'HIC_REL_NO'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHICL1',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HICL_SEQNO', 'HIC_SEQN'),
    ),
    TableSpec(
        table_name='RHICLSQ1_HICLSEQNO_MSTR',
        columns=('HICL_SEQNO', 'GNN', 'GNN60'),
        coercers={'HICL_SEQNO': str, 'GNN': str, 'GNN60': str},
        nullable=frozenset({'GNN', 'GNN60'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHICLSQ1',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HICL_SEQNO',),
    ),
    TableSpec(
        table_name='RHICLSQ2_HICLSEQNO_MSTR',
        columns=('HICL_SEQNO', 'GNN', 'GNN60'),
        coercers={'HICL_SEQNO': str, 'GNN': str, 'GNN60': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RHICLSQ2',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HICL_SEQNO',),
    ),
    TableSpec(
        table_name='RMEDDIN0_RDFMID_INACTV_LINK',
        columns=('ROUTED_DOSAGE_FORM_MED_ID', 'HIC_SEQN', 'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'),
        coercers={'ROUTED_DOSAGE_FORM_MED_ID': str, 'HIC_SEQN': str, 'INACTV_NOT_PRES_CNT': str, 'INACTV_PRES_CNT': str},
        nullable=frozenset({'INACTV_NOT_PRES_CNT', 'INACTV_PRES_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDDIN0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_DOSAGE_FORM_MED_ID', 'HIC_SEQN'),
    ),
    TableSpec(
        table_name='RMEDDIS0_ROUTED_DF_STUDY_TABLE',
        columns=('ROUTED_DOSAGE_FORM_MED_ID', 'TOTAL_PRODUCTS_CNT', 'PRODUCTS_RESEARCHED_CNT'),
        coercers={'ROUTED_DOSAGE_FORM_MED_ID': str, 'TOTAL_PRODUCTS_CNT': str, 'PRODUCTS_RESEARCHED_CNT': str},
        nullable=frozenset({'PRODUCTS_RESEARCHED_CNT', 'TOTAL_PRODUCTS_CNT'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RMEDDIS0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('ROUTED_DOSAGE_FORM_MED_ID',),
    ),
]
