"""B9.C Tier B batch 01 (9 NDC/GCN-keyed join tables).

Tables: RAHFSGC1, RAPPLNA0, RAPPLSL0, RATCGC0, RCQNDC0, RETCGC0, RETCGCH0, RETCHCL0, RETCHIC0.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_01.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='RAHFSGC1_GCNSEQNO_LINK',
        columns=('GCN_SEQNO', 'AHFS8', 'AHFS_REL'),
        coercers={'GCN_SEQNO': str, 'AHFS8': str, 'AHFS_REL': str},
        nullable=frozenset({'AHFS_REL'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RAHFSGC1',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'AHFS8'),
    ),
    TableSpec(
        table_name='RAPPLNA0_FDA_NDC_APPL',
        columns=('NDC', 'APPL_NO', 'APPL_TYPE_CD'),
        coercers={'NDC': str, 'APPL_NO': str, 'APPL_TYPE_CD': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RAPPLNA0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'APPL_NO'),
    ),
    TableSpec(
        table_name='RAPPLSL0_FDA_NDC_NDA_ANDA',
        columns=('NDC', 'NDA_IND', 'ANDA_IND', 'LISTING_SEQ_NO', 'TRADENAME'),
        coercers={'NDC': str, 'NDA_IND': str, 'ANDA_IND': str, 'LISTING_SEQ_NO': str, 'TRADENAME': str},
        nullable=frozenset({'LISTING_SEQ_NO', 'TRADENAME'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RAPPLSL0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'NDA_IND'),
    ),
    TableSpec(
        table_name='RATCGC0_ATC_GCNSEQNO_LINK',
        columns=('GCN_SEQNO', 'ATC', 'ATC_VER'),
        coercers={'GCN_SEQNO': str, 'ATC': str, 'ATC_VER': str},
        nullable=frozenset({'ATC_VER'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RATCGC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'ATC'),
    ),
    TableSpec(
        table_name='RCQNDC0_CLNQTY_NDC',
        columns=('NDC', 'MEDID', 'CLNQTY_SUBUNIT_QTY', 'CLNQTY_SUBUOM_DESC', 'CLNQTY_PKG_DESC', 'CLNQTY_DESC', 'ERX_QTY', 'ERX_SCRIPT_UOM_DESC', 'ERX_SCRIPT_POTUNIT_CD'),
        coercers={'NDC': str, 'MEDID': str, 'CLNQTY_SUBUNIT_QTY': str, 'CLNQTY_SUBUOM_DESC': str, 'CLNQTY_PKG_DESC': str, 'CLNQTY_DESC': str, 'ERX_QTY': str, 'ERX_SCRIPT_UOM_DESC': str, 'ERX_SCRIPT_POTUNIT_CD': str},
        nullable=frozenset({'CLNQTY_PKG_DESC', 'CLNQTY_SUBUNIT_QTY'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RCQNDC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'MEDID'),
    ),
    TableSpec(
        table_name='RETCGC0_ETC_GCNSEQNO',
        columns=('GCN_SEQNO', 'ETC_ID', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND'),
        coercers={'GCN_SEQNO': str, 'ETC_ID': str, 'ETC_COMMON_USE_IND': str, 'ETC_DEFAULT_USE_IND': str},
        nullable=frozenset({'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCGC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'ETC_ID'),
    ),
    TableSpec(
        table_name='RETCGCH0_ETC_GCNSEQNO_HIST',
        columns=('GCN_SEQNO', 'ETC_ID', 'ETC_REVISION_SEQNO', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND', 'ETC_CHANGE_TYPE_CODE', 'ETC_EFFECTIVE_DATE'),
        coercers={'GCN_SEQNO': str, 'ETC_ID': str, 'ETC_REVISION_SEQNO': str, 'ETC_COMMON_USE_IND': str, 'ETC_DEFAULT_USE_IND': str, 'ETC_CHANGE_TYPE_CODE': str, 'ETC_EFFECTIVE_DATE': str},
        nullable=frozenset({'ETC_CHANGE_TYPE_CODE', 'ETC_COMMON_USE_IND', 'ETC_DEFAULT_USE_IND', 'ETC_EFFECTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCGCH0',
        delta_semantics=DeltaSemantics.APPEND_ONLY,
        natural_key=('GCN_SEQNO', 'ETC_ID', 'ETC_REVISION_SEQNO'),
    ),
    TableSpec(
        table_name='RETCHCL0_ETC_HICLSEQNO',
        columns=('HICL_SEQNO', 'ETC_ID'),
        coercers={'HICL_SEQNO': str, 'ETC_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCHCL0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HICL_SEQNO', 'ETC_ID'),
    ),
    TableSpec(
        table_name='RETCHIC0_ETC_HICSEQN',
        columns=('HIC_SEQN', 'ETC_ID'),
        coercers={'HIC_SEQN': str, 'ETC_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RETCHIC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HIC_SEQN', 'ETC_ID'),
    ),
]
