"""B9.C Tier B batch 06 (9 NDC/GCN-keyed join tables).

Tables: ROBCNDC0, RPEIGA0, RPEIGD0, RPEIGR0, RPEIGRR0, RPEIHR0, RPEIMA0, RPEIMD0, RPEIMNR0.
Tests: modules/drug-database/tests/unit/test_fdb_tier_b_batch_06.py
"""
from __future__ import annotations
from drug_database.services.fdb_adapter import DeltaSemantics, TableSpec, Tier


SPECS: list[TableSpec] = [
    TableSpec(
        table_name='ROBCNDC0_OBC_NDC',
        columns=('NDC', 'OBC3', 'GCN', 'GCN_SEQNO', 'GTI'),
        coercers={'NDC': str, 'OBC3': str, 'GCN': str, 'GCN_SEQNO': str, 'GTI': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='ROBCNDC0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('NDC', 'OBC3'),
    ),
    TableSpec(
        table_name='RPEIGA0_GCNSEQNO_ATTRIBUTE',
        columns=('GCN_SEQNO', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN', 'ATTRIBUTE_VALUE', 'LINK_INACTIVE_DATE'),
        coercers={'GCN_SEQNO': str, 'ATTRIBUTE_CODE': str, 'ATTRIBUTE_SN': str, 'ATTRIBUTE_VALUE': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIGA0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN'),
    ),
    TableSpec(
        table_name='RPEIGD0_GCNSEQNO_DF_LINK',
        columns=('GCN_SEQNO', 'DOSAGE_FORM_ID', 'DOSAGE_FORM_TYPE_ID', 'LINK_INACTIVE_DATE'),
        coercers={'GCN_SEQNO': str, 'DOSAGE_FORM_ID': str, 'DOSAGE_FORM_TYPE_ID': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIGD0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'DOSAGE_FORM_ID'),
    ),
    TableSpec(
        table_name='RPEIGR0_GCNSEQNO_RT_RELATION',
        columns=('GCN_SEQNO', 'PARENT_RT_ID', 'CLINICAL_RT_ID', 'RELATION_INACTIVE_DATE'),
        coercers={'GCN_SEQNO': str, 'PARENT_RT_ID': str, 'CLINICAL_RT_ID': str, 'RELATION_INACTIVE_DATE': str},
        nullable=frozenset({'RELATION_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIGR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'PARENT_RT_ID'),
    ),
    TableSpec(
        table_name='RPEIGRR0_GCNSEQNO_REP_RT',
        columns=('GCN_SEQNO', 'REPRESENTATIVE_RT_ID'),
        coercers={'GCN_SEQNO': str, 'REPRESENTATIVE_RT_ID': str},
        nullable=frozenset(),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIGRR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('GCN_SEQNO', 'REPRESENTATIVE_RT_ID'),
    ),
    TableSpec(
        table_name='RPEIHR0_HICLSEQNO_RT_RELATION',
        columns=('HICL_SEQNO', 'PARENT_RT_ID', 'CLINICAL_RT_ID', 'RELATION_INACTIVE_DATE'),
        coercers={'HICL_SEQNO': str, 'PARENT_RT_ID': str, 'CLINICAL_RT_ID': str, 'RELATION_INACTIVE_DATE': str},
        nullable=frozenset({'RELATION_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIHR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('HICL_SEQNO', 'PARENT_RT_ID'),
    ),
    TableSpec(
        table_name='RPEIMA0_MED_ATTRIBUTE',
        columns=('MEDID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN', 'ATTRIBUTE_VALUE', 'LINK_INACTIVE_DATE'),
        coercers={'MEDID': str, 'ATTRIBUTE_CODE': str, 'ATTRIBUTE_SN': str, 'ATTRIBUTE_VALUE': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIMA0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID', 'ATTRIBUTE_CODE', 'ATTRIBUTE_SN'),
    ),
    TableSpec(
        table_name='RPEIMD0_MED_DF_LINK',
        columns=('MEDID', 'DOSAGE_FORM_ID', 'DOSAGE_FORM_TYPE_ID', 'LINK_INACTIVE_DATE'),
        coercers={'MEDID': str, 'DOSAGE_FORM_ID': str, 'DOSAGE_FORM_TYPE_ID': str, 'LINK_INACTIVE_DATE': str},
        nullable=frozenset({'LINK_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIMD0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MEDID', 'DOSAGE_FORM_ID'),
    ),
    TableSpec(
        table_name='RPEIMNR0_MED_NAME_RT_RELATION',
        columns=('MED_NAME_ID', 'PARENT_RT_ID', 'CLINICAL_RT_ID', 'RELATION_INACTIVE_DATE'),
        coercers={'MED_NAME_ID': str, 'PARENT_RT_ID': str, 'CLINICAL_RT_ID': str, 'RELATION_INACTIVE_DATE': str},
        nullable=frozenset({'RELATION_INACTIVE_DATE'}),
        tier=Tier.B,
        loader_group='fdb_tier_b',
        record_counts_key='RPEIMNR0',
        delta_semantics=DeltaSemantics.UPSERT_BY_NATURAL_KEY,
        natural_key=('MED_NAME_ID', 'PARENT_RT_ID'),
    ),
]
