"""Seed the pre-built detection rules from the PRD (50+ rules across 9 categories).

Called on module startup if rules don't exist yet.
"""
from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from src.models.tables import DetectionProfile, DetectionRule

PRE_BUILT_RULES = [
    # ── Universal Rules ───────────────────────────────────────────────────────
    {
        "rule_code": "ALL-001",
        "name": "Duplicate Claim",
        "description": "Same member, same NDC, same DOS, different auth number",
        "category": "duplicate",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "duplicate_claim"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "ALL-002",
        "name": "Phantom Pharmacy",
        "description": "NPI not in NCPDP database or OIG excluded",
        "category": "eligibility",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "phantom_pharmacy"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "ALL-003",
        "name": "Phantom Prescriber",
        "description": "NPI invalid, DEA inactive, or OIG excluded",
        "category": "eligibility",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "phantom_prescriber"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "ALL-004",
        "name": "Days Supply Manipulation",
        "description": "Quantity and days supply inconsistent with NDC packaging/dosing",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "threshold",
        "rule_logic": {"field": "days_supply_deviation_pct", "operator": "gt", "threshold": 0.20},
        "default_parameters": {"threshold": 0.20},
        "default_action": "flag",
        "confidence_scoring": {"medium": 0.20},
        "is_system": True,
    },
    {
        "rule_code": "ALL-005",
        "name": "Early Refill",
        "description": "Fill date before configured percent of previous days supply",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "threshold",
        "rule_logic": {"field": "refill_pct", "operator": "lt", "threshold": 0.75},
        "default_parameters": {"threshold": 0.75},
        "default_action": "flag",
        "confidence_scoring": {"medium": 0.75},
        "is_system": True,
    },
    {
        "rule_code": "ALL-006",
        "name": "Weekend/Holiday Volume Spike",
        "description": "Pharmacy claims volume on weekend/holiday exceeds weekday average",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "post_adjudication",
        "rule_type": "statistical",
        "rule_logic": {"field": "weekend_volume_vs_weekday_ratio", "operator": "gt", "threshold": 2.0},
        "default_parameters": {"threshold": 2.0},
        "default_action": "log",
        "confidence_scoring": {"low": 2.0},
        "is_system": True,
    },
    {
        "rule_code": "ALL-007",
        "name": "Geographic Anomaly",
        "description": "Member filling at pharmacy more than 100 miles from home address",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "threshold",
        "rule_logic": {"field": "geo_distance_miles", "operator": "gt", "threshold": 100},
        "default_parameters": {"threshold": 100},
        "default_action": "flag",
        "confidence_scoring": {"low": 100},
        "is_system": True,
    },
    {
        "rule_code": "ALL-008",
        "name": "Suspicious Network Cluster",
        "description": "Community of entities with >80% self-referral rate and geographic spread >200 miles",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "post_adjudication",
        "rule_type": "composite",
        "rule_logic": {
            "sub_rules": [
                {"field": "self_referral_rate", "operator": "gt", "threshold": 0.80, "rule_type": "threshold"},
                {"field": "geo_spread_miles", "operator": "gt", "threshold": 200, "rule_type": "threshold"},
            ]
        },
        "default_parameters": {"self_referral_threshold": 0.80, "geo_spread_miles": 200},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "ALL-009",
        "name": "Auto-Hold on Critical Investigation",
        "description": "When investigation reaches CRITICAL severity, automatically hold future payments",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "critical_investigation_auto_hold"},
        "default_parameters": {"auto_hold_enabled": True},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "ALL-010",
        "name": "Predictive Watchlist Trigger",
        "description": "Pharmacy 30-day fraud probability exceeds threshold",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "post_adjudication",
        "rule_type": "threshold",
        "rule_logic": {"field": "fraud_probability_30d", "operator": "gt", "threshold": 0.70},
        "default_parameters": {"threshold": 0.70},
        "default_action": "alert",
        "confidence_scoring": {"high": 0.90, "medium": 0.70},
        "is_system": True,
    },
    # ── Manufacturer Rules ─────────────────────────────────────────────────────
    {
        "rule_code": "MFR-001",
        "name": "NQ Inflation",
        "description": "(DV+NQ) exceeds WAC per unit x quantity",
        "category": "pricing_integrity",
        "client_types": ["manufacturer"],
        "detection_mode": "both",
        "rule_type": "threshold",
        "rule_logic": {"field": "nq_to_wac_ratio", "operator": "gt", "threshold": 1.10},
        "default_parameters": {"threshold": 1.10},
        "default_action": "flag",
        "confidence_scoring": {"high": 1.50, "medium": 1.20, "low": 1.10},
        "is_system": True,
    },
    {
        "rule_code": "MFR-002",
        "name": "Bill-Reverse-Rebill",
        "description": "Same pharmacy, NDC, member — reversal then rebill with higher NQ within 14 days",
        "category": "billing_pattern",
        "client_types": ["manufacturer"],
        "detection_mode": "post_adjudication",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "bill_reverse_rebill", "lookback_days": 14},
        "default_parameters": {"lookback_days": 14},
        "default_action": "flag",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "MFR-003",
        "name": "Contracted Rate Deviation",
        "description": "Pharmacy rate deviates from their own historical baseline",
        "category": "pricing_integrity",
        "client_types": ["manufacturer"],
        "detection_mode": "post_adjudication",
        "rule_type": "statistical",
        "rule_logic": {"field": "contracted_rate_deviation_pct", "operator": "gt", "threshold": 0.15},
        "default_parameters": {"threshold": 0.15, "baseline_days": 90},
        "default_action": "flag",
        "confidence_scoring": {"medium": 0.15},
        "is_system": True,
    },
    {
        "rule_code": "MFR-004",
        "name": "Volume Spike",
        "description": "Pharmacy submits more claims for specific NDC vs rolling average",
        "category": "utilization",
        "client_types": ["manufacturer"],
        "detection_mode": "post_adjudication",
        "rule_type": "statistical",
        "rule_logic": {"field": "volume_vs_avg_ratio", "operator": "gt", "threshold": 2.0},
        "default_parameters": {"threshold": 2.0, "rolling_days": 30},
        "default_action": "alert",
        "confidence_scoring": {"medium": 2.0},
        "is_system": True,
    },
    {
        "rule_code": "MFR-005",
        "name": "eVoucher/Coupon Abuse",
        "description": "Same voucher code used for multiple patients or exceeded max uses",
        "category": "billing_pattern",
        "client_types": ["manufacturer"],
        "detection_mode": "real_time",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "voucher_abuse"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "MFR-006",
        "name": "Phantom Patient",
        "description": "Claims for members with no matching enrollment record",
        "category": "eligibility",
        "client_types": ["manufacturer"],
        "detection_mode": "real_time",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "phantom_patient"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "MFR-007",
        "name": "Accumulator/Maximizer Detection",
        "description": "Copay assistance not counting toward member deductible/OOP",
        "category": "accumulator",
        "client_types": ["manufacturer"],
        "detection_mode": "real_time",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "accumulator_maximizer"},
        "default_parameters": {},
        "default_action": "alert",
        "confidence_scoring": {"high": 0.97, "medium": 0.80},
        "is_system": True,
    },
    {
        "rule_code": "MFR-008",
        "name": "Statement Credit Abuse",
        "description": "Statement account pharmacy submitting claims that should be statement-only",
        "category": "billing_pattern",
        "client_types": ["manufacturer"],
        "detection_mode": "real_time",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "statement_credit_abuse"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "MFR-009",
        "name": "Under-Reimbursement Gaming",
        "description": "Pharmacy consistently submitting U&C at minimum to maximize POS adjustment",
        "category": "pricing_integrity",
        "client_types": ["manufacturer"],
        "detection_mode": "post_adjudication",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "uc_minimum_gaming"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    # ── Health Plan Rules ──────────────────────────────────────────────────────
    {
        "rule_code": "HP-001",
        "name": "Network Leakage",
        "description": "Claims filled at out-of-network pharmacies when in-network available within 10 miles",
        "category": "network_compliance",
        "client_types": ["health_plan"],
        "detection_mode": "post_adjudication",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "network_leakage", "in_network_radius_miles": 10},
        "default_parameters": {"in_network_radius_miles": 10},
        "default_action": "log",
        "confidence_scoring": {"low": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "HP-002",
        "name": "Formulary Non-Compliance",
        "description": "Non-formulary drug dispensed without prior authorization",
        "category": "network_compliance",
        "client_types": ["health_plan"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "formulary_non_compliance"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "HP-003",
        "name": "Therapeutic Duplication",
        "description": "Member receiving two drugs from same therapeutic class simultaneously",
        "category": "utilization",
        "client_types": ["health_plan"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "therapeutic_duplication"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "HP-004",
        "name": "Drug-Disease Contraindication",
        "description": "Drug inappropriate for member diagnosed conditions",
        "category": "utilization",
        "client_types": ["health_plan"],
        "detection_mode": "real_time",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "drug_disease_contraindication"},
        "default_parameters": {},
        "default_action": "alert",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "HP-005",
        "name": "Prescriber Outlier",
        "description": "Prescriber volume for specific drug exceeds peer group by 3 standard deviations",
        "category": "utilization",
        "client_types": ["health_plan"],
        "detection_mode": "post_adjudication",
        "rule_type": "statistical",
        "rule_logic": {"field": "prescriber_volume_std_devs", "operator": "gt", "threshold": 3.0},
        "default_parameters": {"threshold": 3.0},
        "default_action": "flag",
        "confidence_scoring": {"medium": 3.0},
        "is_system": True,
    },
    {
        "rule_code": "HP-006",
        "name": "Pharmacy Audit Trigger",
        "description": "Pharmacy flagged on multiple rules exceeding threshold in period",
        "category": "billing_pattern",
        "client_types": ["health_plan"],
        "detection_mode": "post_adjudication",
        "rule_type": "threshold",
        "rule_logic": {"field": "flag_count_30d", "operator": "gt", "threshold": 5},
        "default_parameters": {"threshold": 5, "period_days": 30},
        "default_action": "flag",
        "confidence_scoring": {"high": 5},
        "is_system": True,
    },
    {
        "rule_code": "HP-007",
        "name": "Controlled Substance Monitoring",
        "description": "Opioid MME exceeds CDC guideline, multiple prescribers/pharmacies",
        "category": "controlled_substance",
        "client_types": ["health_plan"],
        "detection_mode": "both",
        "rule_type": "composite",
        "rule_logic": {
            "sub_rules": [
                {"field": "opioid_mme_per_day", "operator": "gt", "threshold": 90, "rule_type": "threshold"},
            ]
        },
        "default_parameters": {"mme_threshold": 90, "max_prescribers": 3, "max_pharmacies": 3},
        "default_action": "alert",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "HP-008",
        "name": "High-Cost Claimant",
        "description": "Member claims exceed configured threshold in period (top 1%)",
        "category": "utilization",
        "client_types": ["health_plan"],
        "detection_mode": "post_adjudication",
        "rule_type": "statistical",
        "rule_logic": {"field": "cost_percentile", "operator": "gte", "threshold": 0.99},
        "default_parameters": {"percentile_threshold": 0.99},
        "default_action": "log",
        "confidence_scoring": {"low": 0.99},
        "is_system": True,
    },
    {
        "rule_code": "HP-009",
        "name": "Inappropriate Quantity",
        "description": "Quantity exceeds FDA max recommended or plan limits",
        "category": "utilization",
        "client_types": ["health_plan"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "quantity_exceeds_limit"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "HP-010",
        "name": "Refill Pattern Anomaly",
        "description": "Member consistently fills exactly on day X (possible auto-refill waste)",
        "category": "utilization",
        "client_types": ["health_plan"],
        "detection_mode": "post_adjudication",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "refill_pattern_anomaly"},
        "default_parameters": {},
        "default_action": "log",
        "confidence_scoring": {"low": 1.0},
        "is_system": True,
    },
    # ── TPA Rules ─────────────────────────────────────────────────────────────
    {
        "rule_code": "TPA-001",
        "name": "Eligibility Mismatch",
        "description": "Claim paid for member not eligible on DOS",
        "category": "eligibility",
        "client_types": ["tpa"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "eligibility_mismatch"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "TPA-002",
        "name": "COB Error",
        "description": "Primary/secondary payer assignment incorrect",
        "category": "billing_pattern",
        "client_types": ["tpa"],
        "detection_mode": "post_adjudication",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "cob_error"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "TPA-003",
        "name": "Plan Design Violation",
        "description": "Benefit applied doesn't match plan configuration",
        "category": "billing_pattern",
        "client_types": ["tpa"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "plan_design_violation"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "TPA-004",
        "name": "Provider Credential Issue",
        "description": "Pharmacy or prescriber credentials expired or suspended",
        "category": "eligibility",
        "client_types": ["tpa"],
        "detection_mode": "real_time",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "credential_issue"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    # ── 340B Rules ────────────────────────────────────────────────────────────
    {
        "rule_code": "340B-001",
        "name": "Duplicate Discount",
        "description": "340B discounted drug also subject to manufacturer rebate for same claim",
        "category": "340b",
        "client_types": ["340b"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "340b_duplicate_discount"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "340B-002",
        "name": "Contract Pharmacy Non-Compliance",
        "description": "Claim from pharmacy not registered as 340B contract pharmacy",
        "category": "340b",
        "client_types": ["340b"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "340b_contract_pharmacy"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "340B-003",
        "name": "Covered Entity Verification",
        "description": "Entity claiming 340B pricing not on HRSA database",
        "category": "340b",
        "client_types": ["340b"],
        "detection_mode": "real_time",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "340b_covered_entity"},
        "default_parameters": {},
        "default_action": "block",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "340B-004",
        "name": "Split Billing Accuracy",
        "description": "340B vs non-340B classification doesn't match patient eligibility",
        "category": "340b",
        "client_types": ["340b"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "340b_split_billing"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "340B-005",
        "name": "Diversion",
        "description": "Drug dispensed to non-eligible patient at 340B pricing",
        "category": "340b",
        "client_types": ["340b"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "340b_diversion"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    # ── Workers Comp Rules ────────────────────────────────────────────────────
    {
        "rule_code": "WC-001",
        "name": "State Formulary Non-Compliance",
        "description": "Drug not on state's workers compensation formulary",
        "category": "workers_comp",
        "client_types": ["workers_comp"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "wc_formulary_non_compliance"},
        "default_parameters": {},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "WC-002",
        "name": "Exceeds State Fee Schedule",
        "description": "Reimbursement exceeds state's WC fee schedule",
        "category": "workers_comp",
        "client_types": ["workers_comp"],
        "detection_mode": "both",
        "rule_type": "threshold",
        "rule_logic": {"field": "fee_schedule_ratio", "operator": "gt", "threshold": 1.0},
        "default_parameters": {"threshold": 1.0},
        "default_action": "flag",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "WC-003",
        "name": "Treatment Duration Exceeded",
        "description": "Fills exceed expected treatment duration for injury type",
        "category": "workers_comp",
        "client_types": ["workers_comp"],
        "detection_mode": "post_adjudication",
        "rule_type": "threshold",
        "rule_logic": {"field": "treatment_duration_ratio", "operator": "gt", "threshold": 1.50},
        "default_parameters": {"threshold": 1.50},
        "default_action": "flag",
        "confidence_scoring": {"medium": 1.50},
        "is_system": True,
    },
    {
        "rule_code": "WC-004",
        "name": "Opioid Guidelines",
        "description": "Opioid prescribing exceeds state WC opioid guidelines",
        "category": "controlled_substance",
        "client_types": ["workers_comp"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "wc_opioid_guideline"},
        "default_parameters": {},
        "default_action": "alert",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    # ── Telehealth Rules ──────────────────────────────────────────────────────
    {
        "rule_code": "TH-001",
        "name": "Telehealth Prescriber Volume",
        "description": "Telehealth prescriber writing more than 50 scripts/day",
        "category": "utilization",
        "client_types": ["all"],
        "detection_mode": "post_adjudication",
        "rule_type": "threshold",
        "rule_logic": {"field": "scripts_per_day", "operator": "gt", "threshold": 50},
        "default_parameters": {"threshold": 50},
        "default_action": "flag",
        "confidence_scoring": {"medium": 50},
        "is_system": True,
    },
    {
        "rule_code": "TH-002",
        "name": "Telehealth Geographic Dispersion",
        "description": "Telehealth prescriber patients spread across more than 10 states",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "post_adjudication",
        "rule_type": "threshold",
        "rule_logic": {"field": "patient_state_count", "operator": "gt", "threshold": 10},
        "default_parameters": {"threshold": 10},
        "default_action": "flag",
        "confidence_scoring": {"medium": 10},
        "is_system": True,
    },
    {
        "rule_code": "TH-003",
        "name": "Telehealth + High-Cost Drug",
        "description": "Telehealth prescriber writing high-cost specialty or GLP-1 drugs at >40% of volume",
        "category": "utilization",
        "client_types": ["all"],
        "detection_mode": "post_adjudication",
        "rule_type": "threshold",
        "rule_logic": {"field": "high_cost_drug_rate", "operator": "gt", "threshold": 0.40},
        "default_parameters": {"threshold": 0.40},
        "default_action": "flag",
        "confidence_scoring": {"medium": 0.40},
        "is_system": True,
    },
    {
        "rule_code": "TH-004",
        "name": "Telehealth + Controlled Substance",
        "description": "Telehealth prescriber writing Schedule II-V controlled substances",
        "category": "controlled_substance",
        "client_types": ["all"],
        "detection_mode": "both",
        "rule_type": "pattern",
        "rule_logic": {"pattern": "telehealth_controlled_substance"},
        "default_parameters": {},
        "default_action": "alert",
        "confidence_scoring": {"high": 1.0},
        "is_system": True,
    },
    {
        "rule_code": "TH-005",
        "name": "Telehealth Prescriber-Pharmacy Affinity",
        "description": "More than 50% of telehealth prescriber scripts filled at single pharmacy",
        "category": "billing_pattern",
        "client_types": ["all"],
        "detection_mode": "post_adjudication",
        "rule_type": "threshold",
        "rule_logic": {"field": "top_pharmacy_share", "operator": "gt", "threshold": 0.50},
        "default_parameters": {"threshold": 0.50},
        "default_action": "flag",
        "confidence_scoring": {"high": 0.50},
        "is_system": True,
    },
]

PRE_BUILT_PROFILES = [
    {
        "name": "Manufacturer Copay Profile",
        "description": "Detection rules for manufacturer copay programs",
        "client_type": "manufacturer",
        "rule_codes": ["ALL-001", "ALL-002", "ALL-003", "ALL-004", "ALL-005", "ALL-006", "ALL-007",
                       "MFR-001", "MFR-002", "MFR-003", "MFR-004", "MFR-005", "MFR-006", "MFR-007"],
        "is_system": True,
    },
    {
        "name": "Health Plan Profile",
        "description": "Detection rules for health plan/PBM programs",
        "client_type": "health_plan",
        "rule_codes": ["ALL-001", "ALL-002", "ALL-003", "ALL-004", "ALL-005", "ALL-006", "ALL-007",
                       "HP-001", "HP-002", "HP-003", "HP-004", "HP-005", "HP-006", "HP-007"],
        "is_system": True,
    },
    {
        "name": "TPA Profile",
        "description": "Detection rules for third-party administrator programs",
        "client_type": "tpa",
        "rule_codes": ["ALL-001", "ALL-002", "ALL-003", "ALL-004", "ALL-005",
                       "TPA-001", "TPA-002", "TPA-003", "TPA-004"],
        "is_system": True,
    },
    {
        "name": "340B Profile",
        "description": "Detection rules for 340B programs",
        "client_type": "340b",
        "rule_codes": ["ALL-001", "ALL-002", "ALL-003",
                       "340B-001", "340B-002", "340B-003", "340B-004", "340B-005"],
        "is_system": True,
    },
    {
        "name": "Workers Compensation Profile",
        "description": "Detection rules for workers compensation programs",
        "client_type": "workers_comp",
        "rule_codes": ["ALL-001", "ALL-002", "ALL-003", "ALL-004", "ALL-005",
                       "WC-001", "WC-002", "WC-003", "WC-004"],
        "is_system": True,
    },
]


def seed_detection_rules(session: Session) -> int:
    """Seed all pre-built detection rules. Returns count of rules created."""
    created = 0
    for rule_data in PRE_BUILT_RULES:
        existing = session.execute(
            select(DetectionRule).where(DetectionRule.rule_code == rule_data["rule_code"])
        ).scalar_one_or_none()
        if existing is None:
            rule = DetectionRule(**rule_data)
            session.add(rule)
            created += 1
    session.flush()

    for profile_data in PRE_BUILT_PROFILES:
        existing_profile = session.execute(
            select(DetectionProfile).where(
                DetectionProfile.name == profile_data["name"],
                DetectionProfile.is_system.is_(True),
            )
        ).scalar_one_or_none()
        if existing_profile is None:
            rule_codes = profile_data["rule_codes"]
            rule_ids = []
            for code in rule_codes:
                rule = session.execute(
                    select(DetectionRule).where(DetectionRule.rule_code == code)
                ).scalar_one_or_none()
                if rule:  # pragma: no branch — all rule codes are seeded above
                    rule_ids.append(rule.id)
            profile_kwargs = {k: v for k, v in profile_data.items() if k != "rule_codes"}
            profile = DetectionProfile(
                **profile_kwargs,
                rule_ids=rule_ids,
            )
            session.add(profile)
    session.flush()
    return created
