"""program_config RLS tenant isolation.

Applies row-level security policies to all 9 tenant-scoped tables
per the Wave 20 B2 pattern. All program_config tables are
tenant-scoped (TenantScopedMixin) — no global-catalog tables here.

SQL generated by ``scripts/apply_rls.py --schema program_config
--dry-run`` and embedded here for auditability.

Revision ID: 0003_pc_rls
Revises: 0002_pc_check_constraints
Create Date: 2026-04-21
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0003_pc_rls"
down_revision: Union[str, None] = "0002_pc_check_constraints"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SCHEMA = "program_config"
_TABLES = (
    "brd_submissions",
    "brd_templates",
    "contracts",
    "manufacturer_program_configs",
    "onboarding_step_log",
    "onboarding_workflows",
    "program_activity_log",
    "program_drugs",
    "programs",
)
import os
_APP_ROLE = os.environ.get("IFX_APP_ROLE", "ifx_dev_app")
_ROLES = f"ifx_dev_app, ifx_mock_app, {_APP_ROLE}"
_PREDICATE = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
)


def upgrade() -> None:
    for table in _TABLES:
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {_SCHEMA}.{table}
              FOR ALL
              TO {_ROLES}
              USING      ({_PREDICATE})
              WITH CHECK ({_PREDICATE});
            """
        )


def downgrade() -> None:
    for table in _TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {_SCHEMA}.{table};")
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {_SCHEMA}.{table} DISABLE ROW LEVEL SECURITY;")
