"""core baseline

Revision ID: 0001_core_baseline
Revises: 
Create Date: 2026-04-12 13:41:04.567248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_core_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusion_list',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('organization_name', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('exclusion_type', sa.String(length=100), nullable=True),
    sa.Column('exclusion_date', sa.Date(), nullable=True),
    sa.Column('reinstate_date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('individual', 'organization')", name=op.f('ck_exclusion_list_exclusion_list_entity_type_valid')),
    sa.CheckConstraint("source IN ('OIG', 'SAM')", name=op.f('ck_exclusion_list_exclusion_list_source_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exclusion_list')),
    schema='core'
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('module', 'action', name='uq_permissions_module_action'),
    schema='core'
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), server_default='#0B1D3A', nullable=True),
    sa.Column('secondary_color', sa.String(length=7), server_default='#FFFFFF', nullable=True),
    sa.Column('font_family', sa.String(length=100), server_default='Inter', nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='America/New_York', nullable=True),
    sa.Column('date_format', sa.String(length=20), server_default='MM/DD/YYYY', nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('data_retention_days', sa.Integer(), server_default='2555', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'suspended', 'terminated')", name=op.f('ck_tenants_tenants_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['core.users.id'], name='fk_tenants_created_by_users', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['core.users.id'], name='fk_tenants_updated_by_users', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug')),
    schema='core'
    )
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False, schema='core')
    op.create_index('ix_tenants_status', 'tenants', ['status'], unique=False, schema='core')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'disabled')", name=op.f('ck_jobs_jobs_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_jobs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    schema='core'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_roles_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    schema='core'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('azure_ad_oid', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'locked')", name=op.f('ck_users_users_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    schema='core'
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='core')
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_audit_log_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    schema='core'
    )
    op.create_index('ix_audit_action', 'audit_log', ['tenant_id', 'action', 'created_at'], unique=False, schema='core')
    op.create_index('ix_audit_entity', 'audit_log', ['tenant_id', 'entity_type', 'entity_id'], unique=False, schema='core')
    op.create_index('ix_audit_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False, schema='core')
    op.create_index('ix_audit_user', 'audit_log', ['tenant_id', 'user_id', 'created_at'], unique=False, schema='core')
    op.create_table('exclusion_matches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('exclusion_list_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_entity_type', sa.String(length=50), nullable=False),
    sa.Column('matched_entity_id', sa.String(length=255), nullable=False),
    sa.Column('match_confidence', sa.String(length=20), server_default='exact', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_confidence IN ('exact', 'probable', 'possible')", name=op.f('ck_exclusion_matches_exclusion_matches_confidence_valid')),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'dismissed')", name=op.f('ck_exclusion_matches_exclusion_matches_status_valid')),
    sa.ForeignKeyConstraint(['exclusion_list_id'], ['core.exclusion_list.id'], name=op.f('fk_exclusion_matches_exclusion_list_id_exclusion_list')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['core.users.id'], name=op.f('fk_exclusion_matches_reviewed_by_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_exclusion_matches_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exclusion_matches')),
    schema='core'
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_files_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['core.users.id'], name=op.f('fk_files_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    schema='core'
    )
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('items_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_failed', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'cancelled')", name=op.f('ck_job_runs_job_runs_status_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['core.jobs.id'], name=op.f('fk_job_runs_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    schema='core'
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_notification_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', 'notification_type', name='uq_notification_prefs_user_type'),
    schema='core'
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='info', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_notifications_notifications_severity_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_notifications_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='core'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['core.permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='pk_role_permissions'),
    schema='core'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['core.users.id'], name=op.f('fk_user_roles_granted_by_users')),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='pk_user_roles'),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_table('notifications', schema='core')
    op.drop_table('notification_preferences', schema='core')
    op.drop_table('job_runs', schema='core')
    op.drop_table('files', schema='core')
    op.drop_table('exclusion_matches', schema='core')
    op.drop_index('ix_audit_user', table_name='audit_log', schema='core')
    op.drop_index('ix_audit_tenant_created', table_name='audit_log', schema='core')
    op.drop_index('ix_audit_entity', table_name='audit_log', schema='core')
    op.drop_index('ix_audit_action', table_name='audit_log', schema='core')
    op.drop_table('audit_log', schema='core')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_table('roles', schema='core')
    op.drop_table('jobs', schema='core')
    op.drop_index('ix_tenants_status', table_name='tenants', schema='core')
    op.drop_index('ix_tenants_slug', table_name='tenants', schema='core')
    op.drop_table('tenants', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_table('exclusion_list', schema='core')
    # ### end Alembic commands ###
